#!/usr/bin/env python3
"""Generate self-contained theme_ui.c for all 10 hub themes (P1).

Each pack duplicates local helpers + shared pages; only HOME layout differs.
Run: python tools/gen_p1_all_themes.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = ROOT / "ui" / "themes"
THEME_IDS = (
    "slate",
    "sand",
    "ink",
    "forest",
    "dusk",
    "ocean",
    "zen",
    "pulse",
    "bloom",
    "metro",
)

HEADER = r'''/**
 * {name} theme pack - self-contained UI (home + all routes).
 * No shared hub_pages_*; events mutate hub_model then refresh/navigate.
 * Generated by tools/gen_p1_all_themes.py - do not hand-edit permanently.
 */
#include "hub_ui.h"
#include "hub_theme.h"
#include "hub_font.h"
#include "hub_model.h"
#include "hub_icons.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>

/* ── local helpers (theme-local, not shared pages) ───────────────── */

static void go_cb(lv_event_t *e)
{{
    hub_ui_go((hub_route_t)(uintptr_t)lv_event_get_user_data(e));
}}

static void scene_cb(lv_event_t *e)
{{
    const char *id = (const char *)lv_event_get_user_data(e);
    hub_model_apply_scene(id);
    hub_ui_refresh();
}}

static void proto_cb(lv_event_t *e)
{{
    const char *id = (const char *)lv_event_get_user_data(e);
    hub_model_toggle_proto(id);
    hub_ui_refresh();
}}

static void room_cb(lv_event_t *e)
{{
    int idx = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_set_room(idx);
    hub_ui_go(HUB_ROUTE_ROOM);
}}

static void arm_cb(lv_event_t *e)
{{
    bool on = (bool)(uintptr_t)lv_event_get_user_data(e);
    hub_model_set_armed(on);
    hub_ui_refresh();
}}

static void zone_cb(lv_event_t *e)
{{
    int cell = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_toggle_zone(cell);
    hub_ui_refresh();
}}

static lv_obj_t *lbl(lv_obj_t *par, const char *txt, lv_color_t c, const lv_font_t *f)
{{
    lv_obj_t *l = lv_label_create(par);
    lv_label_set_text(l, txt ? txt : "");
    hub_style_label(l, c, f);
    return l;
}}

static lv_obj_t *btn_go(lv_obj_t *par, const char *txt, hub_route_t r, bool accent)
{{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *b = lv_btn_create(par);
    lv_obj_remove_style_all(b);
    hub_apply_card(b, accent);
    if (accent) {{
        lv_obj_set_style_bg_color(b, p->accent, 0);
    }}
    lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)r);
    lv_obj_t *l = lv_label_create(b);
    lv_label_set_text(l, txt);
    hub_style_label(l, accent ? p->ink_on : p->t1, hub_font());
    lv_obj_center(l);
    return b;
}}

static void quickbar(lv_obj_t *par)
{{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *bar = lv_obj_create(par);
    lv_obj_remove_style_all(bar);
    lv_obj_set_width(bar, LV_PCT(100));
    lv_obj_set_height(bar, 52);
    lv_obj_set_flex_flow(bar, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(bar, 6, 0);

    struct {{
        hub_ico_t ico;
        const char *t;
        hub_route_t r;
    }} items[] = {{
        {{ HUB_ICO_GRID, "情景", HUB_ROUTE_SCENES }},
        {{ HUB_ICO_SHIELD, "安防", HUB_ROUTE_SECURITY }},
        {{ HUB_ICO_CLOCK, "日程", HUB_ROUTE_SCHEDULE }},
        {{ HUB_ICO_COG, "设置", HUB_ROUTE_SETTINGS }},
    }};
    for (int i = 0; i < 4; i++) {{
        lv_obj_t *b = lv_btn_create(bar);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, false);
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_height(b, LV_PCT(100));
        lv_obj_set_flex_flow(b, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(b, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)items[i].r);
        hub_ico_add(b, items[i].ico, p->accent, 18);
        lbl(b, items[i].t, p->t1, hub_font());
    }}
}}

'''

PAGES = r'''
/* ── ROOM ────────────────────────────────────────────────────────── */

static void toggle_dev_cb(lv_event_t *e)
{
    int kind = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[m->room_idx];
    if (kind == 0) {
        d->ceiling = !d->ceiling;
    } else if (kind == 1) {
        d->strip = d->strip > 0 ? 0 : 55;
    } else if (kind == 3) {
        d->ac_on = !d->ac_on;
    } else if (kind == 4) {
        d->heat_on = !d->heat_on;
    }
    hub_ui_refresh();
}

static void step_ac_cb(lv_event_t *e)
{
    int delta = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_step_ac(delta);
    hub_ui_refresh();
}

static void step_curtain_cb(lv_event_t *e)
{
    int delta = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_step_curtain(delta);
    hub_ui_refresh();
}

static void build_room(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[m->room_idx];

    lv_obj_t *shell = hub_shell_create(parent, hub_model_room_name(m->room_idx), true);
    lv_obj_t *body = hub_shell_body(shell);
    hub_shell_set_dots(shell, 4, 1);

    lv_obj_t *tabs = lv_obj_create(body);
    lv_obj_remove_style_all(tabs);
    lv_obj_set_width(tabs, LV_PCT(100));
    lv_obj_set_height(tabs, 36);
    lv_obj_set_flex_flow(tabs, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(tabs, 6, 0);
    for (int i = 0; i < 4; i++) {
        lv_obj_t *t = lv_btn_create(tabs);
        lv_obj_remove_style_all(t);
        hub_apply_card(t, i == m->room_idx);
        if (i == m->room_idx) {
            lv_obj_set_style_bg_color(t, p->accent, 0);
        }
        lv_obj_set_flex_grow(t, 1);
        lv_obj_set_height(t, LV_PCT(100));
        lv_obj_add_event_cb(t, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        lv_obj_t *tl = lv_label_create(t);
        lv_label_set_text(tl, hub_model_room_name(i));
        hub_style_label(tl, i == m->room_idx ? p->ink_on : p->t1, hub_font());
        lv_obj_center(tl);
    }

    /* 主灯 */
    lv_obj_t *c0 = lv_btn_create(body);
    lv_obj_remove_style_all(c0);
    hub_apply_card(c0, d->ceiling);
    lv_obj_set_width(c0, LV_PCT(100));
    lv_obj_set_height(c0, 56);
    lv_obj_add_event_cb(c0, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(c0, HUB_ICO_BULB, p->accent, 22);
    lv_obj_align(lv_obj_get_child(c0, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c0, "主灯", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c0, 1), LV_ALIGN_LEFT_MID, 40, 0);
    lbl(c0, d->ceiling ? "开" : "关", d->ceiling ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c0, 2), LV_ALIGN_RIGHT_MID, -8, 0);

    /* 灯带 */
    lv_obj_t *c1 = lv_btn_create(body);
    lv_obj_remove_style_all(c1);
    hub_apply_card(c1, d->strip > 0);
    lv_obj_set_width(c1, LV_PCT(100));
    lv_obj_set_height(c1, 56);
    lv_obj_add_event_cb(c1, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)1);
    hub_ico_add(c1, HUB_ICO_BULB, p->warm, 22);
    lv_obj_align(lv_obj_get_child(c1, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c1, "灯带", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c1, 1), LV_ALIGN_LEFT_MID, 40, 0);
    char strip_buf[16];
    snprintf(strip_buf, sizeof(strip_buf), d->strip > 0 ? "%d%%" : "关", d->strip);
    lbl(c1, strip_buf, d->strip > 0 ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c1, 2), LV_ALIGN_RIGHT_MID, -8, 0);

    /* 窗帘 ±10 */
    lv_obj_t *c2 = lv_obj_create(body);
    lv_obj_remove_style_all(c2);
    hub_apply_card(c2, d->curtain > 50);
    lv_obj_set_width(c2, LV_PCT(100));
    lv_obj_set_height(c2, 64);
    hub_ico_add(c2, HUB_ICO_CURTAIN, p->violet, 22);
    lv_obj_align(lv_obj_get_child(c2, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c2, "窗帘", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c2, 1), LV_ALIGN_LEFT_MID, 40, -10);
    char cur_buf[16];
    snprintf(cur_buf, sizeof(cur_buf), "%d%%", d->curtain);
    lbl(c2, cur_buf, p->t2, hub_font());
    lv_obj_align(lv_obj_get_child(c2, 2), LV_ALIGN_LEFT_MID, 40, 10);
    lv_obj_t *cm = lv_btn_create(c2);
    lv_obj_remove_style_all(cm);
    hub_apply_card(cm, false);
    lv_obj_set_size(cm, 40, 40);
    lv_obj_align(cm, LV_ALIGN_RIGHT_MID, -56, 0);
    lv_obj_add_event_cb(cm, step_curtain_cb, LV_EVENT_CLICKED, (void *)(intptr_t)-10);
    hub_ico_add(cm, HUB_ICO_MINUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(cm, 0));
    lv_obj_t *cp = lv_btn_create(c2);
    lv_obj_remove_style_all(cp);
    hub_apply_card(cp, false);
    lv_obj_set_size(cp, 40, 40);
    lv_obj_align(cp, LV_ALIGN_RIGHT_MID, -8, 0);
    lv_obj_add_event_cb(cp, step_curtain_cb, LV_EVENT_CLICKED, (void *)(intptr_t)10);
    hub_ico_add(cp, HUB_ICO_PLUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(cp, 0));

    /* 空调 ± */
    lv_obj_t *c3 = lv_obj_create(body);
    lv_obj_remove_style_all(c3);
    hub_apply_card(c3, d->ac_on);
    lv_obj_set_width(c3, LV_PCT(100));
    lv_obj_set_height(c3, 64);
    hub_ico_add(c3, HUB_ICO_SNOW, p->cool, 22);
    lv_obj_align(lv_obj_get_child(c3, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lv_obj_t *ac_tog = lv_btn_create(c3);
    lv_obj_remove_style_all(ac_tog);
    lv_obj_set_size(ac_tog, 100, 48);
    lv_obj_align(ac_tog, LV_ALIGN_LEFT_MID, 36, 0);
    lv_obj_add_event_cb(ac_tog, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)3);
    lbl(ac_tog, "空调", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(ac_tog, 0), LV_ALIGN_TOP_LEFT, 0, 4);
    char ac_buf[16];
    snprintf(ac_buf, sizeof(ac_buf), d->ac_on ? "%d°" : "关", d->ac_sp);
    lbl(ac_tog, ac_buf, d->ac_on ? p->cool : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ac_tog, 1), LV_ALIGN_BOTTOM_LEFT, 0, -4);
    lv_obj_t *am = lv_btn_create(c3);
    lv_obj_remove_style_all(am);
    hub_apply_card(am, false);
    lv_obj_set_size(am, 40, 40);
    lv_obj_align(am, LV_ALIGN_RIGHT_MID, -56, 0);
    lv_obj_add_event_cb(am, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)-1);
    hub_ico_add(am, HUB_ICO_MINUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(am, 0));
    lv_obj_t *ap = lv_btn_create(c3);
    lv_obj_remove_style_all(ap);
    hub_apply_card(ap, false);
    lv_obj_set_size(ap, 40, 40);
    lv_obj_align(ap, LV_ALIGN_RIGHT_MID, -8, 0);
    lv_obj_add_event_cb(ap, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)1);
    hub_ico_add(ap, HUB_ICO_PLUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(ap, 0));

    /* 地暖 */
    lv_obj_t *c4 = lv_btn_create(body);
    lv_obj_remove_style_all(c4);
    hub_apply_card(c4, d->heat_on);
    lv_obj_set_width(c4, LV_PCT(100));
    lv_obj_set_height(c4, 56);
    lv_obj_add_event_cb(c4, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)4);
    hub_ico_add(c4, HUB_ICO_HEAT, p->heat, 22);
    lv_obj_align(lv_obj_get_child(c4, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c4, "地暖", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c4, 1), LV_ALIGN_LEFT_MID, 40, 0);
    lbl(c4, d->heat_on ? "开" : "关", d->heat_on ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c4, 2), LV_ALIGN_RIGHT_MID, -8, 0);
}

/* ── SCENES ──────────────────────────────────────────────────────── */

static void build_scenes(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *shell = hub_shell_create(parent, "情景", true);
    lv_obj_t *body = hub_shell_body(shell);
    hub_shell_set_dots(shell, 4, 2);

    struct {
        const char *id;
        const char *name;
        const char *sub;
        hub_ico_t ico;
    } sc[] = {
        { "home", "回家", "灯+空调", HUB_ICO_HOME },
        { "away", "离家", "全关布防", HUB_ICO_AWAY },
        { "movie", "观影", "影院灯光", HUB_ICO_LAYERS },
        { "sleep", "睡眠", "夜间模式", HUB_ICO_MOON },
        { "guest", "会客", "明亮会客", HUB_ICO_BULB },
        { "eco", "节能", "低功耗", HUB_ICO_GAUGE },
    };
    lv_obj_t *grid = lv_obj_create(body);
    lv_obj_remove_style_all(grid);
    lv_obj_set_size(grid, LV_PCT(100), LV_PCT(100));
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 8, 0);
    lv_obj_set_style_pad_column(grid, 8, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);
    for (int i = 0; i < 6; i++) {
        bool active = strcmp(m->active_scene, sc[i].id) == 0;
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, active);
        if (active) {
            lv_obj_set_style_bg_color(b, p->accent, 0);
        }
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, scene_cb, LV_EVENT_CLICKED, (void *)sc[i].id);
        hub_ico_add(b, sc[i].ico, active ? p->ink_on : p->accent, 22);
        lv_obj_align(lv_obj_get_child(b, 0), LV_ALIGN_TOP_LEFT, 8, 8);
        lv_obj_t *n = lv_label_create(b);
        lv_label_set_text(n, sc[i].name);
        hub_style_label(n, active ? p->ink_on : p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_LEFT_MID, 8, 4);
        lv_obj_t *s = lv_label_create(b);
        lv_label_set_text(s, sc[i].sub);
        hub_style_label(s, active ? p->ink_on : p->t3, hub_font());
        lv_obj_align(s, LV_ALIGN_BOTTOM_LEFT, 8, -8);
    }
}

/* ── ENERGY / GATEWAY / SETTINGS / NETWORK / SECURITY / SCHEDULE ── */

static void build_energy(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *shell = hub_shell_create(parent, "能耗", true);
    lv_obj_t *body = hub_shell_body(shell);
    hub_shell_set_dots(shell, 4, 3);
    lv_obj_t *card = lv_obj_create(body);
    lv_obj_remove_style_all(card);
    lv_obj_set_width(card, LV_PCT(100));
    lv_obj_set_height(card, 120);
    hub_apply_card(card, true);
    hub_ico_add(card, HUB_ICO_GAUGE, p->accent, 24);
    lv_obj_align(lv_obj_get_child(card, 0), LV_ALIGN_TOP_RIGHT, -8, 8);
    lbl(card, "整屋功率", p->t3, hub_font());
    char buf[32];
    snprintf(buf, sizeof(buf), "%.2f kW", (double)m->power_kw);
    lv_obj_t *v = lv_label_create(card);
    lv_label_set_text(v, buf);
    hub_style_label(v, p->accent, hub_font_clock());
    lv_obj_align(v, LV_ALIGN_LEFT_MID, 0, 4);
    lv_obj_t *tip = lv_btn_create(card);
    lv_obj_remove_style_all(tip);
    lv_obj_add_event_cb(tip, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_GATEWAY);
    lv_obj_align(tip, LV_ALIGN_BOTTOM_LEFT, 0, 0);
    lbl(tip, "查看计量总线 →", p->t2, hub_font());

    lv_obj_t *row = lv_obj_create(body);
    lv_obj_remove_style_all(row);
    lv_obj_set_width(row, LV_PCT(100));
    lv_obj_set_flex_grow(row, 1);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(row, 8, 0);
    char a[32], b[32], c[32];
    snprintf(a, sizeof(a), "室内 %.1f°", (double)m->indoor_c);
    snprintf(b, sizeof(b), "湿度 %d%%", m->rh);
    snprintf(c, sizeof(c), "今日 %.1fkWh", (double)(12.0 + m->power_kw * 2));
    const char *labs[] = { a, b, c };
    for (int i = 0; i < 3; i++) {
        lv_obj_t *x = lv_obj_create(row);
        lv_obj_remove_style_all(x);
        hub_apply_card(x, false);
        lv_obj_set_flex_grow(x, 1);
        lv_obj_set_height(x, LV_PCT(100));
        lv_obj_t *l = lv_label_create(x);
        lv_label_set_text(l, labs[i]);
        hub_style_label(l, p->t2, hub_font());
        lv_obj_center(l);
    }
}

static void build_gateway(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *shell = hub_shell_create(parent, "总线", true);
    lv_obj_t *body = hub_shell_body(shell);
    lbl(body, "协议健康度 · 点击切换", p->t2, hub_font());
    for (int i = 0; i < HUB_PROTO_COUNT; i++) {
        lv_obj_t *card = lv_btn_create(body);
        lv_obj_remove_style_all(card);
        hub_apply_card(card, m->protos[i].ok);
        lv_obj_set_width(card, LV_PCT(100));
        lv_obj_set_height(card, 64);
        lv_obj_add_event_cb(card, proto_cb, LV_EVENT_CLICKED, (void *)m->protos[i].id);
        hub_ico_add(card, HUB_ICO_BUS, m->protos[i].ok ? p->on : p->alert, 20);
        lv_obj_align(lv_obj_get_child(card, 0), LV_ALIGN_LEFT_MID, 4, 0);
        lv_obj_t *n = lv_label_create(card);
        lv_label_set_text(n, m->protos[i].name);
        hub_style_label(n, p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_TOP_LEFT, 36, 8);
        char buf[16];
        snprintf(buf, sizeof(buf), m->protos[i].ok ? "%d%%" : "故障", m->protos[i].health);
        lv_obj_t *st = lv_label_create(card);
        lv_label_set_text(st, buf);
        hub_style_label(st, m->protos[i].ok ? p->on : p->alert, hub_font());
        lv_obj_align(st, LV_ALIGN_RIGHT_MID, 0, 0);
        lv_obj_t *bar = lv_bar_create(card);
        lv_obj_set_size(bar, LV_PCT(70), 8);
        lv_bar_set_range(bar, 0, 100);
        lv_bar_set_value(bar, m->protos[i].health, LV_ANIM_OFF);
        lv_obj_set_style_bg_color(bar, m->protos[i].ok ? p->accent : p->alert, LV_PART_INDICATOR);
        lv_obj_align(bar, LV_ALIGN_BOTTOM_LEFT, 36, -8);
    }
}

static void build_settings(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *shell = hub_shell_create(parent, "设置", true);
    lv_obj_t *body = hub_shell_body(shell);
    struct {
        hub_ico_t ico;
        const char *t;
        const char *s;
        hub_route_t r;
    } rows[] = {
        { HUB_ICO_WIFI, "网络与配网", "Wi-Fi / 以太网", HUB_ROUTE_NETWORK },
        { HUB_ICO_SHIELD, "安防", "布防 / 撤防", HUB_ROUTE_SECURITY },
        { HUB_ICO_BUS, "总线", "MQTT / Modbus", HUB_ROUTE_GATEWAY },
        { HUB_ICO_HOME, "房间", "控件布局", HUB_ROUTE_ROOM },
        { HUB_ICO_CLOCK, "日程", "定时与场景", HUB_ROUTE_SCHEDULE },
    };
    for (int i = 0; i < 5; i++) {
        lv_obj_t *row = lv_btn_create(body);
        lv_obj_remove_style_all(row);
        hub_apply_card(row, false);
        lv_obj_set_width(row, LV_PCT(100));
        lv_obj_set_height(row, 56);
        lv_obj_add_event_cb(row, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)rows[i].r);
        hub_ico_add(row, rows[i].ico, p->accent, 20);
        lv_obj_align(lv_obj_get_child(row, 0), LV_ALIGN_LEFT_MID, 8, 0);
        lv_obj_t *t = lv_label_create(row);
        lv_label_set_text(t, rows[i].t);
        hub_style_label(t, p->t1, hub_font());
        lv_obj_align(t, LV_ALIGN_LEFT_MID, 40, -8);
        lv_obj_t *s = lv_label_create(row);
        lv_label_set_text(s, rows[i].s);
        hub_style_label(s, p->t3, hub_font());
        lv_obj_align(s, LV_ALIGN_LEFT_MID, 40, 10);
        hub_ico_label(row, HUB_ICO_RIGHT, p->t4);
        lv_obj_align(lv_obj_get_child(row, -1), LV_ALIGN_RIGHT_MID, -4, 0);
    }
}

static void build_network(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *shell = hub_shell_create(parent, "网络", true);
    lv_obj_t *body = hub_shell_body(shell);
    lv_obj_t *card = lv_btn_create(body);
    lv_obj_remove_style_all(card);
    hub_apply_card(card, m->protos[3].ok);
    lv_obj_set_width(card, LV_PCT(100));
    lv_obj_set_height(card, 96);
    lv_obj_add_event_cb(card, proto_cb, LV_EVENT_CLICKED, (void *)"wifi");
    hub_ico_add(card, m->protos[3].ok ? HUB_ICO_WIFI : HUB_ICO_WIFI_OFF, p->accent, 28);
    lv_obj_align(lv_obj_get_child(card, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lv_obj_t *t = lv_label_create(card);
    lv_label_set_text(t, m->protos[3].ok ? "Wi-Fi · Office-AP" : "Wi-Fi · 已关闭");
    hub_style_label(t, p->t1, hub_font());
    lv_obj_align(t, LV_ALIGN_LEFT_MID, 48, -14);
    lv_obj_t *s = lv_label_create(card);
    lv_label_set_text(s, "点击切换 · 192.168.1.50");
    hub_style_label(s, p->t3, hub_font());
    lv_obj_align(s, LV_ALIGN_LEFT_MID, 48, 8);
}

static char s_pin_buf[5];

static void pin_cb(lv_event_t *e)
{
    const char *key = (const char *)lv_event_get_user_data(e);
    if (!key) {
        return;
    }
    if (key[0] == 'C') {
        s_pin_buf[0] = '\0';
    } else if (key[0] == 'O') {
        if (strcmp(s_pin_buf, "1234") == 0) {
            hub_model_set_armed(false);
        }
        s_pin_buf[0] = '\0';
    } else {
        size_t n = strlen(s_pin_buf);
        if (n < 4) {
            s_pin_buf[n] = key[0];
            s_pin_buf[n + 1] = '\0';
        }
    }
    hub_ui_refresh();
}

static void build_security(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *shell = hub_shell_create(parent, "安防", true);
    lv_obj_t *body = hub_shell_body(shell);
    lv_obj_t *card = lv_obj_create(body);
    lv_obj_remove_style_all(card);
    hub_apply_card(card, m->armed);
    lv_obj_set_size(card, LV_PCT(100), 100);
    hub_ico_add(card, HUB_ICO_SHIELD, m->armed ? p->on : p->t3, 36);
    lv_obj_align(lv_obj_get_child(card, 0), LV_ALIGN_TOP_MID, 0, 10);
    lv_obj_t *t = lv_label_create(card);
    lv_label_set_text(t, m->armed ? "已布防 · Away" : "已撤防 · Home");
    hub_style_label(t, m->armed ? p->on : p->t2, hub_font());
    lv_obj_align(t, LV_ALIGN_BOTTOM_MID, 0, -12);

    lv_obj_t *row = lv_obj_create(body);
    lv_obj_remove_style_all(row);
    lv_obj_set_width(row, LV_PCT(100));
    lv_obj_set_height(row, 40);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(row, 8, 0);
    lv_obj_t *arm = lv_btn_create(row);
    lv_obj_remove_style_all(arm);
    hub_apply_card(arm, true);
    lv_obj_set_style_bg_color(arm, p->accent, 0);
    lv_obj_set_flex_grow(arm, 1);
    lv_obj_set_height(arm, LV_PCT(100));
    lv_obj_add_event_cb(arm, arm_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)true);
    lv_obj_t *al = lv_label_create(arm);
    lv_label_set_text(al, "布防");
    hub_style_label(al, p->ink_on, hub_font());
    lv_obj_center(al);
    lv_obj_t *dis = lv_btn_create(row);
    lv_obj_remove_style_all(dis);
    hub_apply_card(dis, false);
    lv_obj_set_flex_grow(dis, 1);
    lv_obj_set_height(dis, LV_PCT(100));
    lv_obj_add_event_cb(dis, arm_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)false);
    lv_obj_t *dl = lv_label_create(dis);
    lv_label_set_text(dl, "撤防");
    hub_style_label(dl, p->t1, hub_font());
    lv_obj_center(dl);

    char dots[8];
    size_t pn = strlen(s_pin_buf);
    for (size_t i = 0; i < 4; i++) {
        dots[i] = (i < pn) ? '*' : '-';
    }
    dots[4] = '\0';
    lbl(body, dots, p->t2, hub_font_clock());

    lv_obj_t *pad = lv_obj_create(body);
    lv_obj_remove_style_all(pad);
    lv_obj_set_width(pad, LV_PCT(100));
    lv_obj_set_flex_grow(pad, 1);
    lv_obj_set_layout(pad, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(pad, 6, 0);
    lv_obj_set_style_pad_column(pad, 6, 0);
    static lv_coord_t pc[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t pr[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(pad, pc, pr);
    const char *keys[] = {
        "1", "2", "3",
        "4", "5", "6",
        "7", "8", "9",
        "C", "0", "O",
    };
    const char *labs[] = {
        "1", "2", "3",
        "4", "5", "6",
        "7", "8", "9",
        "C", "0", "OK",
    };
    for (int i = 0; i < 12; i++) {
        lv_obj_t *k = lv_btn_create(pad);
        lv_obj_remove_style_all(k);
        hub_apply_card(k, false);
        lv_obj_set_grid_cell(k, LV_GRID_ALIGN_STRETCH, i % 3, 1, LV_GRID_ALIGN_STRETCH, i / 3, 1);
        lv_obj_add_event_cb(k, pin_cb, LV_EVENT_CLICKED, (void *)keys[i]);
        lv_obj_t *kl = lv_label_create(k);
        lv_label_set_text(kl, labs[i]);
        hub_style_label(kl, p->t1, hub_font());
        lv_obj_center(kl);
    }
}

static void build_schedule(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *shell = hub_shell_create(parent, "日程", true);
    lv_obj_t *body = hub_shell_body(shell);
    struct {
        const char *n;
        const char *t;
        const char *scene;
    } rows[] = {
        { "晨起唤醒", "07:00 · 每天", "morning" },
        { "夜间模式", "22:30 · 每天", "sleep" },
        { "离家布防", "09:00 · 工作日", "away" },
    };
    for (int i = 0; i < 3; i++) {
        lv_obj_t *card = lv_btn_create(body);
        lv_obj_remove_style_all(card);
        hub_apply_card(card, false);
        lv_obj_set_width(card, LV_PCT(100));
        lv_obj_set_height(card, 64);
        lv_obj_add_event_cb(card, scene_cb, LV_EVENT_CLICKED, (void *)rows[i].scene);
        hub_ico_add(card, HUB_ICO_CLOCK, p->accent, 20);
        lv_obj_align(lv_obj_get_child(card, 0), LV_ALIGN_LEFT_MID, 8, 0);
        lv_obj_t *n = lv_label_create(card);
        lv_label_set_text(n, rows[i].n);
        hub_style_label(n, p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_TOP_LEFT, 40, 8);
        lv_obj_t *t = lv_label_create(card);
        lv_label_set_text(t, rows[i].t);
        hub_style_label(t, p->t3, hub_font());
        lv_obj_align(t, LV_ALIGN_BOTTOM_LEFT, 40, -8);
        lbl(card, "执行", p->accent, hub_font());
        lv_obj_align(lv_obj_get_child(card, -1), LV_ALIGN_RIGHT_MID, -8, 0);
    }
}

/* ── entry ───────────────────────────────────────────────────────── */

void hub_theme_build(lv_obj_t *parent, hub_route_t route)
{
    switch (route) {
    case HUB_ROUTE_HOME: build_home(parent); break;
    case HUB_ROUTE_ROOM: build_room(parent); break;
    case HUB_ROUTE_SCENES: build_scenes(parent); break;
    case HUB_ROUTE_ENERGY: build_energy(parent); break;
    case HUB_ROUTE_GATEWAY: build_gateway(parent); break;
    case HUB_ROUTE_SETTINGS: build_settings(parent); break;
    case HUB_ROUTE_NETWORK: build_network(parent); break;
    case HUB_ROUTE_SECURITY: build_security(parent); break;
    case HUB_ROUTE_SCHEDULE: build_schedule(parent); break;
    default: build_home(parent); break;
    }
}
'''

# ── per-theme HOME layouts ─────────────────────────────────────────

HOMES: dict[str, str] = {}

HOMES["slate"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();

    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 14, 0);
    lv_obj_set_style_pad_row(root, 10, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 40);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    hub_clock_label(head, p->t1, hub_font_clock());
    lbl(head, "Slate Hub", p->t1, hub_font());
    lv_obj_t *wifi = lv_btn_create(head);
    lv_obj_remove_style_all(wifi);
    lv_obj_add_event_cb(wifi, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_NETWORK);
    hub_ico_add(wifi, m->protos[3].ok ? HUB_ICO_WIFI : HUB_ICO_WIFI_OFF, p->accent, 20);

    lv_obj_t *pills = lv_obj_create(root);
    lv_obj_remove_style_all(pills);
    lv_obj_set_width(pills, LV_PCT(100));
    lv_obj_set_height(pills, 28);
    lv_obj_set_flex_flow(pills, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(pills, 6, 0);
    for (int i = 0; i < 3; i++) {
        lv_obj_t *pill = lv_btn_create(pills);
        lv_obj_remove_style_all(pill);
        lv_obj_set_height(pill, LV_PCT(100));
        lv_obj_set_style_pad_hor(pill, 10, 0);
        lv_obj_set_style_radius(pill, 999, 0);
        lv_obj_set_style_bg_color(pill, p->bg_card2, 0);
        lv_obj_set_style_bg_opa(pill, LV_OPA_COVER, 0);
        lv_obj_add_event_cb(pill, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_GATEWAY);
        lv_obj_t *l = lv_label_create(pill);
        lv_label_set_text(l, m->protos[i].name);
        hub_style_label(l, m->protos[i].ok ? p->on : p->alert, hub_font());
        lv_obj_center(l);
    }

    lv_obj_t *metrics = lv_obj_create(root);
    lv_obj_remove_style_all(metrics);
    lv_obj_set_width(metrics, LV_PCT(100));
    lv_obj_set_height(metrics, 72);
    lv_obj_set_flex_flow(metrics, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(metrics, 8, 0);
    char mv0[24], mv1[24], mv2[24];
    snprintf(mv0, sizeof(mv0), "%.1fkW", (double)m->power_kw);
    snprintf(mv1, sizeof(mv1), "%.1f°", (double)m->indoor_c);
    snprintf(mv2, sizeof(mv2), "%d%%", m->rh);
    const char *mvs[] = { mv0, mv1, mv2 };
    const char *mls[] = { "功率", "室内", "湿度" };
    hub_route_t mrs[] = { HUB_ROUTE_ENERGY, HUB_ROUTE_ROOM, HUB_ROUTE_ROOM };
    for (int i = 0; i < 3; i++) {
        lv_obj_t *c = lv_btn_create(metrics);
        lv_obj_remove_style_all(c);
        hub_apply_card(c, false);
        lv_obj_set_flex_grow(c, 1);
        lv_obj_set_height(c, LV_PCT(100));
        lv_obj_add_event_cb(c, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)mrs[i]);
        lv_obj_t *v = lv_label_create(c);
        lv_label_set_text(v, mvs[i]);
        hub_style_label(v, p->accent, hub_font());
        lv_obj_align(v, LV_ALIGN_TOP_MID, 0, 8);
        lv_obj_t *l = lv_label_create(c);
        lv_label_set_text(l, mls[i]);
        hub_style_label(l, p->t3, hub_font());
        lv_obj_align(l, LV_ALIGN_BOTTOM_MID, 0, -8);
    }

    lv_obj_t *grid = lv_obj_create(root);
    lv_obj_remove_style_all(grid);
    lv_obj_set_width(grid, LV_PCT(100));
    lv_obj_set_flex_grow(grid, 1);
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 8, 0);
    lv_obj_set_style_pad_column(grid, 8, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);
    for (int i = 0; i < 4; i++) {
        bool on = hub_model_room_active(i);
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_set_style_border_side(b, LV_BORDER_SIDE_LEFT, 0);
        lv_obj_set_style_border_width(b, 3, 0);
        lv_obj_set_style_border_color(b, p->accent, 0);
        lv_obj_set_flex_flow(b, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(b, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        hub_ico_add(b, HUB_ICO_HOME, p->accent, 22);
        lbl(b, hub_model_room_name(i), p->t1, hub_font());
        lbl(b, on ? "运行" : "待机", on ? p->on : p->t3, hub_font());
    }

    quickbar(root);
}
'''

HOMES["sand"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 18, 0);
    lv_obj_set_style_pad_row(root, 8, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *top = lv_obj_create(root);
    lv_obj_remove_style_all(top);
    lv_obj_set_width(top, LV_PCT(100));
    lv_obj_set_height(top, 110);
    lv_obj_set_flex_flow(top, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(top, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);

    lv_obj_t *left = lv_obj_create(top);
    lv_obj_remove_style_all(left);
    lv_obj_set_flex_grow(left, 1);
    lv_obj_set_height(left, LV_PCT(100));
    lv_obj_set_flex_flow(left, LV_FLEX_FLOW_COLUMN);
    lbl(left, "SAND HUB", p->accent, hub_font());
    hub_clock_label(left, p->t1, hub_font_clock_lg());
    char clim[64];
    snprintf(clim, sizeof(clim), "室内 %.1f° · 湿度 %d%% · %.1f kW",
             (double)m->indoor_c, m->rh, (double)m->power_kw);
    lbl(left, clim, p->t3, hub_font());

    lv_obj_t *pwr = lv_btn_create(top);
    lv_obj_remove_style_all(pwr);
    hub_apply_card(pwr, false);
    lv_obj_set_size(pwr, 72, 72);
    lv_obj_set_style_radius(pwr, LV_RADIUS_CIRCLE, 0);
    lv_obj_add_event_cb(pwr, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    hub_ico_add(pwr, HUB_ICO_GAUGE, p->accent, 22);
    lv_obj_align(lv_obj_get_child(pwr, 0), LV_ALIGN_TOP_MID, 0, 10);
    char pb[16];
    snprintf(pb, sizeof(pb), "%.1f", (double)m->power_kw);
    lv_obj_t *pv = lv_label_create(pwr);
    lv_label_set_text(pv, pb);
    hub_style_label(pv, p->t1, hub_font());
    lv_obj_align(pv, LV_ALIGN_BOTTOM_MID, 0, -10);

    const char *subs[] = {"空调 · 窗帘 · 灯", "地暖 · 灯光", "插座 · 水阀", "灯光 · 窗帘"};
    for (int i = 0; i < 4; i++) {
        bool on = hub_model_room_active(i);
        lv_obj_t *row = lv_btn_create(root);
        lv_obj_remove_style_all(row);
        hub_apply_card(row, on);
        lv_obj_set_width(row, LV_PCT(100));
        lv_obj_set_height(row, 52);
        lv_obj_add_event_cb(row, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        hub_ico_add(row, HUB_ICO_HOME, on ? p->accent : p->t3, 22);
        lv_obj_align(lv_obj_get_child(row, 0), LV_ALIGN_LEFT_MID, 8, 0);
        lv_obj_t *n = lv_label_create(row);
        lv_label_set_text(n, hub_model_room_name(i));
        hub_style_label(n, p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_LEFT_MID, 44, -10);
        lv_obj_t *d = lv_label_create(row);
        lv_label_set_text(d, subs[i]);
        hub_style_label(d, p->t3, hub_font());
        lv_obj_align(d, LV_ALIGN_LEFT_MID, 44, 10);
        lv_obj_t *st = lv_label_create(row);
        lv_label_set_text(st, on ? "运行" : "待机");
        hub_style_label(st, on ? p->on : p->t4, hub_font());
        lv_obj_align(st, LV_ALIGN_RIGHT_MID, -8, 0);
    }
    quickbar(root);
    lv_obj_t *cta = lv_obj_create(root);
    lv_obj_remove_style_all(cta);
    lv_obj_set_width(cta, LV_PCT(100));
    lv_obj_set_height(cta, 44);
    lv_obj_set_flex_flow(cta, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(cta, 8, 0);
    lv_obj_t *h = lv_btn_create(cta);
    lv_obj_remove_style_all(h);
    hub_apply_card(h, false);
    lv_obj_set_flex_grow(h, 1);
    lv_obj_set_height(h, LV_PCT(100));
    lv_obj_add_event_cb(h, scene_cb, LV_EVENT_CLICKED, (void *)"home");
    lv_obj_t *hl = lv_label_create(h);
    lv_label_set_text(hl, "回家");
    hub_style_label(hl, p->t1, hub_font());
    lv_obj_center(hl);
    lv_obj_t *a = lv_btn_create(cta);
    lv_obj_remove_style_all(a);
    hub_apply_card(a, true);
    lv_obj_set_style_bg_color(a, p->accent, 0);
    lv_obj_set_flex_grow(a, 1);
    lv_obj_set_height(a, LV_PCT(100));
    lv_obj_add_event_cb(a, scene_cb, LV_EVENT_CLICKED, (void *)"away");
    lv_obj_t *al = lv_label_create(a);
    lv_label_set_text(al, "离家");
    hub_style_label(al, p->ink_on, hub_font());
    lv_obj_center(al);
}
'''

HOMES["ink"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_ROW);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *rail = lv_obj_create(root);
    lv_obj_remove_style_all(rail);
    lv_obj_set_size(rail, 112, 480);
    lv_obj_set_style_pad_all(rail, 12, 0);
    lv_obj_set_style_pad_row(rail, 8, 0);
    lv_obj_set_style_border_width(rail, 1, 0);
    lv_obj_set_style_border_side(rail, LV_BORDER_SIDE_RIGHT, 0);
    lv_obj_set_style_border_color(rail, p->line, 0);
    lv_obj_set_flex_flow(rail, LV_FLEX_FLOW_COLUMN);
    lbl(rail, "INK", p->accent, hub_font());
    hub_clock_label(rail, p->t1, hub_font_clock());
    for (int i = 0; i < 3; i++) {
        lv_obj_t *b = lv_btn_create(rail);
        lv_obj_remove_style_all(b);
        lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_GATEWAY);
        lbl(b, m->protos[i].name, m->protos[i].ok ? p->on : p->alert, hub_font());
    }
    lv_obj_t *pwr = btn_go(rail, "PWR", HUB_ROUTE_ENERGY, true);
    lv_obj_set_width(pwr, LV_PCT(100));
    lv_obj_set_height(pwr, 36);

    lv_obj_t *mainw = lv_obj_create(root);
    lv_obj_remove_style_all(mainw);
    lv_obj_set_flex_grow(mainw, 1);
    lv_obj_set_height(mainw, 480);
    lv_obj_set_style_pad_all(mainw, 12, 0);
    lv_obj_set_style_pad_row(mainw, 8, 0);
    lv_obj_set_flex_flow(mainw, LV_FLEX_FLOW_COLUMN);

    lv_obj_t *mt = lv_obj_create(mainw);
    lv_obj_remove_style_all(mt);
    lv_obj_set_width(mt, LV_PCT(100));
    lv_obj_set_height(mt, 28);
    lv_obj_set_flex_flow(mt, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(mt, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lbl(mt, "ZONE MATRIX", p->t1, hub_font());
    lv_obj_t *go = lv_btn_create(mt);
    lv_obj_remove_style_all(go);
    lv_obj_add_event_cb(go, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    lbl(go, "客厅 →", p->accent, hub_font());

    lv_obj_t *grid = lv_obj_create(mainw);
    lv_obj_remove_style_all(grid);
    lv_obj_set_width(grid, LV_PCT(100));
    lv_obj_set_flex_grow(grid, 1);
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 6, 0);
    lv_obj_set_style_pad_column(grid, 6, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);
    const char *cells[] = {"L1", "L2", "AC", "HEAT", "CUR", "SHUT", "FAN", "PUMP", "VALVE"};
    bool ons[] = {d->ceiling, d->strip > 0, d->ac_on, d->heat_on, d->curtain > 50,
                  d->curtain > 80, d->ac_on, d->heat_on, d->ceiling};
    for (int i = 0; i < 9; i++) {
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, ons[i]);
        if (ons[i]) {
            lv_obj_set_style_bg_color(b, p->accent, 0);
        }
        lv_obj_set_style_radius(b, p->radius, 0);
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 3, 1, LV_GRID_ALIGN_STRETCH, i / 3, 1);
        lv_obj_add_event_cb(b, zone_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        lv_obj_t *l = lv_label_create(b);
        lv_label_set_text(l, cells[i]);
        hub_style_label(l, ons[i] ? p->ink_on : p->t1, hub_font());
        lv_obj_center(l);
    }
    quickbar(mainw);
}
'''

HOMES["forest"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    hub_theme_wash(root, p->accent, LV_OPA_20);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 14, 0);
    lv_obj_set_style_pad_row(root, 8, 0);
    lv_obj_set_flex_align(root, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 36);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    hub_clock_label(head, p->t1, hub_font());
    lbl(head, "Forest", p->t1, hub_font());
    lv_obj_t *eco = btn_go(head, "Eco", HUB_ROUTE_ENERGY, true);
    lv_obj_set_size(eco, 56, 28);

    lv_obj_t *ring = lv_btn_create(root);
    lv_obj_remove_style_all(ring);
    lv_obj_set_size(ring, 148, 148);
    lv_obj_set_style_radius(ring, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(ring, 10, 0);
    lv_obj_set_style_border_color(ring, p->accent, 0);
    lv_obj_set_style_bg_opa(ring, LV_OPA_TRANSP, 0);
    lv_obj_add_event_cb(ring, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    lbl(ring, "今日用电", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ring, 0), LV_ALIGN_CENTER, 0, -28);
    char kwh[16];
    snprintf(kwh, sizeof(kwh), "%.1f", (double)(12.0 + m->power_kw * 2));
    lv_obj_t *kv = lv_label_create(ring);
    lv_label_set_text(kv, kwh);
    hub_style_label(kv, p->t1, hub_font_clock());
    lv_obj_align(kv, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t *ku = lv_label_create(ring);
    lv_label_set_text(ku, "kWh");
    hub_style_label(ku, p->t3, hub_font());
    lv_obj_align(ku, LV_ALIGN_CENTER, 0, 28);

    lv_obj_t *stats = lv_obj_create(root);
    lv_obj_remove_style_all(stats);
    lv_obj_set_width(stats, LV_PCT(100));
    lv_obj_set_height(stats, 48);
    lv_obj_set_flex_flow(stats, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(stats, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    char ib[16], rb[16];
    snprintf(ib, sizeof(ib), "%.0f°", (double)m->indoor_c);
    snprintf(rb, sizeof(rb), "%d%%", m->rh);
    const char *vals[] = { ib, rb, hub_model_ok_count() == HUB_PROTO_COUNT ? "OK" : "CHK" };
    const char *labs[] = { "室内", "湿度", "总线" };
    hub_route_t rts[] = { HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_GATEWAY };
    for (int i = 0; i < 3; i++) {
        lv_obj_t *b = lv_btn_create(stats);
        lv_obj_remove_style_all(b);
        lv_obj_set_size(b, 90, 48);
        lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)rts[i]);
        lv_obj_t *v = lv_label_create(b);
        lv_label_set_text(v, vals[i]);
        hub_style_label(v, (i == 2 && hub_model_ok_count() == HUB_PROTO_COUNT) ? p->on : p->t1, hub_font());
        lv_obj_align(v, LV_ALIGN_TOP_MID, 0, 2);
        lv_obj_t *l = lv_label_create(b);
        lv_label_set_text(l, labs[i]);
        hub_style_label(l, p->t3, hub_font());
        lv_obj_align(l, LV_ALIGN_BOTTOM_MID, 0, -2);
    }

    lv_obj_t *scenes = lv_obj_create(root);
    lv_obj_remove_style_all(scenes);
    lv_obj_set_width(scenes, LV_PCT(100));
    lv_obj_set_flex_grow(scenes, 1);
    lv_obj_set_flex_flow(scenes, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_style_pad_row(scenes, 8, 0);
    lv_obj_set_style_pad_column(scenes, 8, 0);
    const char *ids[] = {"morning", "guest", "movie", "sleep", "eco", "alloff"};
    const char *slabs[] = {"晨起", "会客", "影院", "睡眠模式", "节能", "全关"};
    for (int i = 0; i < 6; i++) {
        bool on = strcmp(m->active_scene, ids[i]) == 0
                  || (strcmp(ids[i], "alloff") == 0 && strcmp(m->active_scene, "away") == 0);
        lv_obj_t *b = lv_btn_create(scenes);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        if (on) {
            lv_obj_set_style_bg_color(b, p->accent, 0);
        }
        lv_obj_set_style_radius(b, 999, 0);
        lv_obj_set_height(b, 36);
        lv_obj_set_style_pad_hor(b, 12, 0);
        lv_obj_add_event_cb(b, scene_cb, LV_EVENT_CLICKED, (void *)ids[i]);
        lv_obj_t *l = lv_label_create(b);
        lv_label_set_text(l, slabs[i]);
        hub_style_label(l, on ? p->ink_on : p->t1, hub_font());
        lv_obj_center(l);
    }
    quickbar(root);
}
'''

HOMES["dusk"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    hub_theme_wash(root, p->violet, LV_OPA_30);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 16, 0);
    lv_obj_set_style_pad_row(root, 10, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 72);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_t *hl = lv_obj_create(head);
    lv_obj_remove_style_all(hl);
    lv_obj_set_flex_flow(hl, LV_FLEX_FLOW_COLUMN);
    lbl(hl, "DUSK", p->violet, hub_font());
    hub_clock_label(hl, p->t1, hub_font_clock_lg());
    lv_obj_t *sec = lv_btn_create(head);
    lv_obj_remove_style_all(sec);
    hub_apply_card(sec, m->armed);
    lv_obj_set_size(sec, 100, 56);
    lv_obj_add_event_cb(sec, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_SECURITY);
    hub_ico_add(sec, HUB_ICO_SHIELD, m->armed ? p->on : p->t3, 18);
    lv_obj_align(lv_obj_get_child(sec, 0), LV_ALIGN_TOP_RIGHT, -8, 6);
    lbl(sec, "安防", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(sec, 1), LV_ALIGN_BOTTOM_LEFT, 8, -8);
    lbl(sec, m->armed ? "已布防" : "撤防", m->armed ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(sec, 2), LV_ALIGN_BOTTOM_RIGHT, -8, -8);

    lv_obj_t *grid = lv_obj_create(root);
    lv_obj_remove_style_all(grid);
    lv_obj_set_width(grid, LV_PCT(100));
    lv_obj_set_flex_grow(grid, 1);
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 8, 0);
    lv_obj_set_style_pad_column(grid, 8, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(12), LV_GRID_FR(10), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);

    lv_obj_t *ac = lv_btn_create(grid);
    lv_obj_remove_style_all(ac);
    hub_apply_card(ac, d->ac_on);
    lv_obj_set_grid_cell(ac, LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_STRETCH, 0, 2);
    lv_obj_add_event_cb(ac, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(ac, HUB_ICO_SNOW, p->cool, 28);
    lv_obj_align(lv_obj_get_child(ac, 0), LV_ALIGN_TOP_LEFT, 12, 12);
    lbl(ac, "客厅空调", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ac, 1), LV_ALIGN_BOTTOM_LEFT, 12, -48);
    char acb[16];
    snprintf(acb, sizeof(acb), d->ac_on ? "%d°" : "--°", d->ac_sp);
    lv_obj_t *av = lv_label_create(ac);
    lv_label_set_text(av, acb);
    hub_style_label(av, p->t1, hub_font_clock_lg());
    lv_obj_align(av, LV_ALIGN_BOTTOM_LEFT, 12, -8);

    int lights = 0;
    for (int i = 0; i < HUB_ROOM_COUNT; i++) {
        if (m->rooms[i].ceiling || m->rooms[i].strip > 0) {
            lights++;
        }
    }
    lv_obj_t *li = lv_btn_create(grid);
    lv_obj_remove_style_all(li);
    hub_apply_card(li, lights > 0);
    lv_obj_set_grid_cell(li, LV_GRID_ALIGN_STRETCH, 1, 1, LV_GRID_ALIGN_STRETCH, 0, 1);
    lv_obj_add_event_cb(li, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(li, HUB_ICO_BULB, p->warm, 22);
    lv_obj_align(lv_obj_get_child(li, 0), LV_ALIGN_TOP_LEFT, 10, 10);
    lbl(li, "灯光", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(li, 1), LV_ALIGN_BOTTOM_LEFT, 10, -22);
    char lb[16];
    snprintf(lb, sizeof(lb), "%d / 4 房间", lights);
    lbl(li, lb, p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(li, 2), LV_ALIGN_BOTTOM_LEFT, 10, -6);

    lv_obj_t *cu = lv_btn_create(grid);
    lv_obj_remove_style_all(cu);
    hub_apply_card(cu, d->curtain > 50);
    lv_obj_set_grid_cell(cu, LV_GRID_ALIGN_STRETCH, 1, 1, LV_GRID_ALIGN_STRETCH, 1, 1);
    lv_obj_add_event_cb(cu, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(cu, HUB_ICO_CURTAIN, p->violet, 22);
    lv_obj_align(lv_obj_get_child(cu, 0), LV_ALIGN_TOP_LEFT, 10, 10);
    lbl(cu, "窗帘", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(cu, 1), LV_ALIGN_BOTTOM_LEFT, 10, -22);
    char cb[16];
    snprintf(cb, sizeof(cb), "%d%% 开", d->curtain);
    lbl(cu, cb, p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(cu, 2), LV_ALIGN_BOTTOM_LEFT, 10, -6);

    lv_obj_t *strip = lv_obj_create(root);
    lv_obj_remove_style_all(strip);
    lv_obj_set_width(strip, LV_PCT(100));
    lv_obj_set_height(strip, 40);
    lv_obj_set_flex_flow(strip, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(strip, 8, 0);
    const char *ids[] = {"home", "movie", "sleep"};
    const char *labs[] = {"回家", "观影", "睡眠模式"};
    for (int i = 0; i < 3; i++) {
        bool on = strcmp(m->active_scene, ids[i]) == 0;
        lv_obj_t *b = lv_btn_create(strip);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        if (on) {
            lv_obj_set_style_bg_color(b, p->accent, 0);
        }
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_height(b, LV_PCT(100));
        lv_obj_add_event_cb(b, scene_cb, LV_EVENT_CLICKED, (void *)ids[i]);
        lv_obj_t *l = lv_label_create(b);
        lv_label_set_text(l, labs[i]);
        hub_style_label(l, on ? p->ink_on : p->t1, hub_font());
        lv_obj_center(l);
    }
    quickbar(root);
}
'''

HOMES["ocean"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 12, 0);
    lv_obj_set_style_pad_row(root, 8, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 36);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    hub_clock_label(head, p->t1, hub_font());
    lbl(head, "Ocean Hub", p->t1, hub_font());
    lv_obj_t *lan = lv_btn_create(head);
    lv_obj_remove_style_all(lan);
    hub_apply_card(lan, m->protos[3].ok);
    if (m->protos[3].ok) {
        lv_obj_set_style_bg_color(lan, p->accent, 0);
    }
    lv_obj_set_size(lan, 52, 26);
    lv_obj_set_style_radius(lan, 999, 0);
    lv_obj_add_event_cb(lan, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_NETWORK);
    lv_obj_t *ll = lv_label_create(lan);
    lv_label_set_text(ll, m->protos[3].ok ? "LAN" : "OFF");
    hub_style_label(ll, m->protos[3].ok ? p->ink_on : p->alert, hub_font());
    lv_obj_center(ll);

    lv_obj_t *hero = lv_btn_create(root);
    lv_obj_remove_style_all(hero);
    hub_apply_card(hero, false);
    lv_obj_set_width(hero, LV_PCT(100));
    lv_obj_set_height(hero, 72);
    lv_obj_add_event_cb(hero, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    char a[32], b[32];
    snprintf(a, sizeof(a), "%.2f kW", (double)m->power_kw);
    snprintf(b, sizeof(b), "%d / 48", m->online_pts);
    lv_obj_t *l1 = lv_label_create(hero);
    lv_label_set_text(l1, "整屋功率");
    hub_style_label(l1, p->t3, hub_font());
    lv_obj_align(l1, LV_ALIGN_TOP_LEFT, 0, 4);
    lv_obj_t *v1 = lv_label_create(hero);
    lv_label_set_text(v1, a);
    hub_style_label(v1, p->accent, hub_font_clock());
    lv_obj_align(v1, LV_ALIGN_BOTTOM_LEFT, 0, -4);
    lv_obj_t *l2 = lv_label_create(hero);
    lv_label_set_text(l2, "在线设备");
    hub_style_label(l2, p->t3, hub_font());
    lv_obj_align(l2, LV_ALIGN_TOP_RIGHT, 0, 4);
    lv_obj_t *v2 = lv_label_create(hero);
    lv_label_set_text(v2, b);
    hub_style_label(v2, p->t1, hub_font_clock());
    lv_obj_align(v2, LV_ALIGN_BOTTOM_RIGHT, 0, -4);

    lbl(root, "协议健康度 · 点击切换", p->t2, hub_font());
    for (int i = 0; i < 3; i++) {
        lv_obj_t *row = lv_btn_create(root);
        lv_obj_remove_style_all(row);
        lv_obj_set_width(row, LV_PCT(100));
        lv_obj_set_height(row, 40);
        lv_obj_set_style_pad_all(row, 0, 0);
        lv_obj_add_event_cb(row, proto_cb, LV_EVENT_CLICKED, (void *)m->protos[i].id);
        lv_obj_t *n = lv_label_create(row);
        lv_label_set_text(n, m->protos[i].name);
        hub_style_label(n, p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_TOP_LEFT, 0, 0);
        char pct[16];
        snprintf(pct, sizeof(pct), m->protos[i].ok ? "%d%%" : "FAULT", m->protos[i].health);
        lv_obj_t *st = lv_label_create(row);
        lv_label_set_text(st, pct);
        hub_style_label(st, m->protos[i].ok ? p->on : p->alert, hub_font());
        lv_obj_align(st, LV_ALIGN_TOP_RIGHT, 0, 0);
        lv_obj_t *bar = lv_bar_create(row);
        lv_obj_set_size(bar, LV_PCT(100), 8);
        lv_bar_set_range(bar, 0, 100);
        lv_bar_set_value(bar, m->protos[i].health, LV_ANIM_OFF);
        lv_obj_set_style_bg_color(bar, m->protos[i].ok ? p->accent : p->alert, LV_PART_INDICATOR);
        lv_obj_align(bar, LV_ALIGN_BOTTOM_MID, 0, 0);
    }

    lv_obj_t *nav = lv_obj_create(root);
    lv_obj_remove_style_all(nav);
    lv_obj_set_width(nav, LV_PCT(100));
    lv_obj_set_height(nav, 56);
    lv_obj_set_flex_flow(nav, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(nav, 8, 0);
    struct { hub_ico_t ico; const char *t; hub_route_t r; } navs[] = {
        { HUB_ICO_HOME, "房间", HUB_ROUTE_ROOM },
        { HUB_ICO_LAYERS, "点表", HUB_ROUTE_GATEWAY },
        { HUB_ICO_COG, "设置", HUB_ROUTE_SETTINGS },
    };
    for (int i = 0; i < 3; i++) {
        lv_obj_t *b = lv_btn_create(nav);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, false);
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_height(b, LV_PCT(100));
        lv_obj_set_flex_flow(b, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(b, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)navs[i].r);
        hub_ico_add(b, navs[i].ico, p->accent, 20);
        lbl(b, navs[i].t, p->t1, hub_font());
    }
    quickbar(root);
}
'''

HOMES["zen"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];
    bool on = hub_model_room_active(0);
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 28, 0);
    lv_obj_set_style_pad_row(root, 12, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 100);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_t *hl = lv_obj_create(head);
    lv_obj_remove_style_all(hl);
    lv_obj_set_flex_flow(hl, LV_FLEX_FLOW_COLUMN);
    lbl(hl, "ZEN", p->t3, hub_font());
    hub_clock_label(hl, p->t1, hub_font_clock_lg());
    lv_obj_t *arm = lv_btn_create(head);
    lv_obj_remove_style_all(arm);
    lv_obj_add_event_cb(arm, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_SECURITY);
    lbl(arm, m->armed ? "ARMED" : "HOME", m->armed ? p->on : p->t3, hub_font());

    lv_obj_t *line = lv_obj_create(root);
    lv_obj_remove_style_all(line);
    lv_obj_set_size(line, LV_PCT(100), 1);
    lv_obj_set_style_bg_color(line, p->line, 0);
    lv_obj_set_style_bg_opa(line, LV_OPA_COVER, 0);

    lv_obj_t *focus = lv_btn_create(root);
    lv_obj_remove_style_all(focus);
    lv_obj_set_width(focus, LV_PCT(100));
    lv_obj_set_flex_grow(focus, 1);
    lv_obj_add_event_cb(focus, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    lbl(focus, "FOCUS ROOM", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(focus, 0), LV_ALIGN_TOP_LEFT, 0, 20);
    lv_obj_t *rn = lv_label_create(focus);
    lv_label_set_text(rn, hub_model_room_name(0));
    hub_style_label(rn, p->t1, hub_font_clock());
    lv_obj_align(rn, LV_ALIGN_LEFT_MID, 0, 0);
    char sub[64];
    snprintf(sub, sizeof(sub), "%s · %s · %.1fkW · 点击进入",
             on ? "运行中" : "静音",
             d->ac_on ? "空调开" : "空调关",
             (double)m->power_kw);
    lbl(focus, sub, p->t2, hub_font());
    lv_obj_align(lv_obj_get_child(focus, 2), LV_ALIGN_BOTTOM_LEFT, 0, -20);

    quickbar(root);

    lv_obj_t *foot = lv_obj_create(root);
    lv_obj_remove_style_all(foot);
    lv_obj_set_width(foot, LV_PCT(100));
    lv_obj_set_height(foot, 52);
    lv_obj_set_flex_flow(foot, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_border_width(foot, 1, 0);
    lv_obj_set_style_border_side(foot, LV_BORDER_SIDE_TOP, 0);
    lv_obj_set_style_border_color(foot, p->line, 0);
    lv_obj_t *fs = btn_go(foot, "设置", HUB_ROUTE_SETTINGS, false);
    lv_obj_set_flex_grow(fs, 1);
    lv_obj_set_height(fs, LV_PCT(100));
    lv_obj_t *fc = btn_go(foot, "情景", HUB_ROUTE_SCENES, false);
    lv_obj_set_flex_grow(fc, 1);
    lv_obj_set_height(fc, LV_PCT(100));
    lv_obj_t *fa = lv_btn_create(foot);
    lv_obj_remove_style_all(fa);
    hub_apply_card(fa, true);
    lv_obj_set_style_bg_color(fa, p->t1, 0);
    lv_obj_set_flex_grow(fa, 1);
    lv_obj_set_height(fa, LV_PCT(100));
    lv_obj_add_event_cb(fa, scene_cb, LV_EVENT_CLICKED, (void *)"alloff");
    lv_obj_t *fal = lv_label_create(fa);
    lv_label_set_text(fal, "全部关闭");
    hub_style_label(fal, p->ink_on, hub_font());
    lv_obj_center(fal);
}
'''

HOMES["pulse"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    hub_theme_wash(root, p->accent, LV_OPA_20);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 12, 0);
    lv_obj_set_style_pad_row(root, 8, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 36);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    hub_clock_label(head, p->accent, hub_font());
    lbl(head, "PULSE // NODE", p->t2, hub_font());
    char link[16];
    snprintf(link, sizeof(link), "LINK %d/%d", hub_model_ok_count(), HUB_PROTO_COUNT);
    lbl(head, link, p->on, hub_font());

    lv_obj_t *hud = lv_obj_create(root);
    lv_obj_remove_style_all(hud);
    lv_obj_set_width(hud, LV_PCT(100));
    lv_obj_set_height(hud, 100);
    lv_obj_set_flex_flow(hud, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(hud, 8, 0);

    lv_obj_t *pwr = lv_btn_create(hud);
    lv_obj_remove_style_all(pwr);
    hub_apply_card(pwr, false);
    lv_obj_set_flex_grow(pwr, 12);
    lv_obj_set_height(pwr, LV_PCT(100));
    lv_obj_add_event_cb(pwr, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    lbl(pwr, "PWR_DRAW", p->accent, hub_font());
    lv_obj_align(lv_obj_get_child(pwr, 0), LV_ALIGN_TOP_LEFT, 8, 8);
    char pb[16];
    snprintf(pb, sizeof(pb), "%.2f", (double)m->power_kw);
    lv_obj_t *pv = lv_label_create(pwr);
    lv_label_set_text(pv, pb);
    hub_style_label(pv, p->accent, hub_font_clock());
    lv_obj_align(pv, LV_ALIGN_LEFT_MID, 8, 4);
    lbl(pwr, "kW", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(pwr, 2), LV_ALIGN_LEFT_MID, 90, 8);

    lv_obj_t *bus = lv_btn_create(hud);
    lv_obj_remove_style_all(bus);
    hub_apply_card(bus, false);
    lv_obj_set_flex_grow(bus, 10);
    lv_obj_set_height(bus, LV_PCT(100));
    lv_obj_add_event_cb(bus, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_GATEWAY);
    lbl(bus, "BUS_HEALTH", p->violet, hub_font());
    lv_obj_align(lv_obj_get_child(bus, 0), LV_ALIGN_TOP_LEFT, 8, 6);
    for (int i = 0; i < 3; i++) {
        char line[24];
        snprintf(line, sizeof(line), "%s %s", m->protos[i].name, m->protos[i].ok ? "OK" : "ERR");
        lv_obj_t *l = lv_label_create(bus);
        lv_label_set_text(l, line);
        hub_style_label(l, m->protos[i].ok ? p->on : p->alert, hub_font());
        lv_obj_align(l, LV_ALIGN_TOP_LEFT, 8, 24 + i * 18);
    }

    lbl(root, "ZONE_SELECT", p->t3, hub_font());
    lv_obj_t *zones = lv_obj_create(root);
    lv_obj_remove_style_all(zones);
    lv_obj_set_width(zones, LV_PCT(100));
    lv_obj_set_flex_grow(zones, 1);
    lv_obj_set_layout(zones, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(zones, 8, 0);
    lv_obj_set_style_pad_column(zones, 8, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(zones, cols, rows);
    for (int i = 0; i < 4; i++) {
        bool active = hub_model_room_active(i);
        lv_obj_t *b = lv_btn_create(zones);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, active);
        if (active) {
            lv_obj_set_style_border_color(b, p->accent, 0);
            lv_obj_set_style_border_width(b, 2, 0);
        }
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        char zid[8];
        snprintf(zid, sizeof(zid), "Z%d", i + 1);
        lbl(b, zid, p->accent, hub_font());
        lv_obj_align(lv_obj_get_child(b, 0), LV_ALIGN_TOP_LEFT, 8, 8);
        lbl(b, hub_model_room_name(i), p->t1, hub_font());
        lv_obj_align(lv_obj_get_child(b, 1), LV_ALIGN_LEFT_MID, 8, 0);
        lbl(b, active ? "ACTIVE" : "IDLE", active ? p->on : p->t4, hub_font());
        lv_obj_align(lv_obj_get_child(b, 2), LV_ALIGN_BOTTOM_LEFT, 8, -8);
    }

    quickbar(root);
    lv_obj_t *sc = lv_obj_create(root);
    lv_obj_remove_style_all(sc);
    lv_obj_set_width(sc, LV_PCT(100));
    lv_obj_set_height(sc, 36);
    lv_obj_set_flex_flow(sc, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(sc, 8, 0);
    lv_obj_t *sh = lv_btn_create(sc);
    lv_obj_remove_style_all(sh);
    hub_apply_card(sh, false);
    lv_obj_set_flex_grow(sh, 1);
    lv_obj_set_height(sh, LV_PCT(100));
    lv_obj_add_event_cb(sh, scene_cb, LV_EVENT_CLICKED, (void *)"home");
    lbl(sh, "SCENE_HOME", p->accent, hub_font());
    lv_obj_center(lv_obj_get_child(sh, 0));
    lv_obj_t *sa = lv_btn_create(sc);
    lv_obj_remove_style_all(sa);
    hub_apply_card(sa, false);
    lv_obj_set_flex_grow(sa, 1);
    lv_obj_set_height(sa, LV_PCT(100));
    lv_obj_add_event_cb(sa, scene_cb, LV_EVENT_CLICKED, (void *)"away");
    lbl(sa, "SCENE_AWAY", p->alert, hub_font());
    lv_obj_center(lv_obj_get_child(sa, 0));
    lv_obj_t *cf = btn_go(sc, "CFG", HUB_ROUTE_SETTINGS, false);
    lv_obj_set_flex_grow(cf, 1);
    lv_obj_set_height(cf, LV_PCT(100));
}
'''

HOMES["bloom"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    hub_theme_wash(root, p->accent, LV_OPA_30);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 18, 0);
    lv_obj_set_style_pad_row(root, 8, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 72);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_t *hl = lv_obj_create(head);
    lv_obj_remove_style_all(hl);
    lv_obj_set_flex_flow(hl, LV_FLEX_FLOW_COLUMN);
    lbl(hl, "Bloom", p->accent, hub_font());
    hub_clock_label(hl, p->t1, hub_font_clock());
    lv_obj_t *orb = lv_btn_create(head);
    lv_obj_remove_style_all(orb);
    hub_apply_card(orb, d->ac_on);
    lv_obj_set_size(orb, 64, 64);
    lv_obj_set_style_radius(orb, LV_RADIUS_CIRCLE, 0);
    lv_obj_add_event_cb(orb, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(orb, HUB_ICO_SNOW, p->cool, 20);
    lv_obj_align(lv_obj_get_child(orb, 0), LV_ALIGN_TOP_MID, 0, 10);
    char acb[16];
    snprintf(acb, sizeof(acb), d->ac_on ? "%d°" : "--", d->ac_sp);
    lbl(orb, acb, p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(orb, 1), LV_ALIGN_BOTTOM_MID, 0, -8);

    lv_obj_t *grid = lv_obj_create(root);
    lv_obj_remove_style_all(grid);
    lv_obj_set_width(grid, LV_PCT(100));
    lv_obj_set_flex_grow(grid, 1);
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 10, 0);
    lv_obj_set_style_pad_column(grid, 10, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);
    for (int i = 0; i < 4; i++) {
        bool on = hub_model_room_active(i);
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        lv_obj_set_style_radius(b, 28, 0);
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        hub_ico_add(b, HUB_ICO_HOME, p->accent, 20);
        lv_obj_align(lv_obj_get_child(b, 0), LV_ALIGN_TOP_LEFT, 14, 14);
        lbl(b, hub_model_room_name(i), p->t1, hub_font());
        lv_obj_align(lv_obj_get_child(b, 1), LV_ALIGN_BOTTOM_LEFT, 14, -28);
        lbl(b, on ? "柔光开启" : "已入睡", p->t3, hub_font());
        lv_obj_align(lv_obj_get_child(b, 2), LV_ALIGN_BOTTOM_LEFT, 14, -10);
    }

    quickbar(root);
    lv_obj_t *pills = lv_obj_create(root);
    lv_obj_remove_style_all(pills);
    lv_obj_set_width(pills, LV_PCT(100));
    lv_obj_set_height(pills, 40);
    lv_obj_set_flex_flow(pills, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(pills, 8, 0);
    const char *ids[] = {"home", "movie", "sleep"};
    const char *labs[] = {"回家", "观影", "晚安"};
    for (int i = 0; i < 3; i++) {
        bool on = strcmp(m->active_scene, ids[i]) == 0;
        lv_obj_t *b = lv_btn_create(pills);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        if (on) {
            lv_obj_set_style_bg_color(b, p->accent, 0);
        }
        lv_obj_set_style_radius(b, 999, 0);
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_height(b, LV_PCT(100));
        lv_obj_add_event_cb(b, scene_cb, LV_EVENT_CLICKED, (void *)ids[i]);
        lv_obj_t *l = lv_label_create(b);
        lv_label_set_text(l, labs[i]);
        hub_style_label(l, on ? p->ink_on : p->t1, hub_font());
        lv_obj_center(l);
    }
}
'''

HOMES["metro"] = r'''
static void build_home(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    lv_obj_t *root = lv_obj_create(parent);
    lv_obj_remove_style_all(root);
    lv_obj_set_size(root, 480, 480);
    hub_apply_screen_bg(root);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(root, 8, 0);
    lv_obj_set_style_pad_row(root, 6, 0);
    lv_obj_clear_flag(root, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *head = lv_obj_create(root);
    lv_obj_remove_style_all(head);
    lv_obj_set_width(head, LV_PCT(100));
    lv_obj_set_height(head, 36);
    lv_obj_set_flex_flow(head, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(head, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    hub_clock_label(head, p->t1, hub_font());
    lbl(head, "Metro Hub", p->t1, hub_font());
    lv_obj_t *set = lv_btn_create(head);
    lv_obj_remove_style_all(set);
    lv_obj_add_event_cb(set, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_SETTINGS);
    lbl(set, "设置", p->t2, hub_font());

    lv_obj_t *grid = lv_obj_create(root);
    lv_obj_remove_style_all(grid);
    lv_obj_set_width(grid, LV_PCT(100));
    lv_obj_set_flex_grow(grid, 1);
    lv_obj_set_layout(grid, LV_LAYOUT_GRID);
    lv_obj_set_style_pad_row(grid, 6, 0);
    lv_obj_set_style_pad_column(grid, 6, 0);
    static lv_coord_t cols[] = { LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST };
    static lv_coord_t rows[] = { LV_GRID_FR(125), LV_GRID_FR(100), LV_GRID_FR(100), LV_GRID_TEMPLATE_LAST };
    lv_obj_set_grid_dsc_array(grid, cols, rows);
    char sub0[16], sub1[16], sub_e[16], sub_b[16];
    snprintf(sub0, sizeof(sub0), "%s", hub_model_room_active(0) ? "运行" : "待机");
    snprintf(sub1, sizeof(sub1), "%s", hub_model_room_active(1) ? "运行" : "待机");
    snprintf(sub_e, sizeof(sub_e), "%.1f kW", (double)m->power_kw);
    snprintf(sub_b, sizeof(sub_b), "%d/%d", hub_model_ok_count(), HUB_PROTO_COUNT);
    const char *labels[] = {"客厅", "主卧", "厨房", "情景", "总线", "能耗", "安防", "设置"};
    const char *subs[] = {sub0, sub1, "4 pts", m->active_scene, sub_b, sub_e,
                          m->armed ? "布防" : "撤防", "CFG"};
    lv_color_t colors[] = {
        LV_COLOR_MAKE(0x00, 0xbc, 0xf2), LV_COLOR_MAKE(0x87, 0x64, 0xb8), LV_COLOR_MAKE(0x10, 0x7c, 0x10),
        LV_COLOR_MAKE(0xff, 0x8c, 0x00), LV_COLOR_MAKE(0xe7, 0x48, 0x56), LV_COLOR_MAKE(0x00, 0x78, 0xd4),
        LV_COLOR_MAKE(0x5d, 0x5a, 0x58), LV_COLOR_MAKE(0x00, 0x78, 0xd4),
    };
    uint8_t cs[] = {2, 1, 1, 1, 1, 1, 1, 1};
    uint8_t col[] = {0, 2, 0, 1, 2, 0, 1, 2};
    uint8_t row[] = {0, 0, 1, 1, 1, 2, 2, 2};
    int rooms[] = {0, 1, 2, -1, -1, -1, -1, -1};
    hub_route_t routes[] = {
        HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_SCENES,
        HUB_ROUTE_GATEWAY, HUB_ROUTE_ENERGY, HUB_ROUTE_SECURITY, HUB_ROUTE_SETTINGS,
    };
    for (int i = 0; i < 8; i++) {
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        lv_obj_set_style_bg_color(b, colors[i], 0);
        lv_obj_set_style_bg_opa(b, LV_OPA_COVER, 0);
        lv_obj_set_style_radius(b, 0, 0);
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, col[i], cs[i], LV_GRID_ALIGN_STRETCH, row[i], 1);
        if (rooms[i] >= 0) {
            lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)rooms[i]);
        } else {
            lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)routes[i]);
        }
        lv_obj_t *n = lv_label_create(b);
        lv_label_set_text(n, labels[i]);
        hub_style_label(n, lv_color_hex(0xffffff), cs[i] == 2 ? hub_font_clock() : hub_font());
        lv_obj_align(n, LV_ALIGN_BOTTOM_LEFT, 10, -22);
        lv_obj_t *s = lv_label_create(b);
        lv_label_set_text(s, subs[i]);
        hub_style_label(s, lv_color_hex(0xffffff), hub_font());
        lv_obj_align(s, LV_ALIGN_BOTTOM_LEFT, 10, -4);
    }
    quickbar(root);
}
'''


def wrap(theme_id: str, home: str) -> str:
    name = theme_id.capitalize()
    return HEADER.format(name=name) + "/* ── HOME ────────────────────────────────────────────────────────── */\n" + home.strip() + "\n\n" + PAGES.lstrip("\n")


def main() -> None:
    written = []
    for tid in THEME_IDS:
        home = HOMES[tid]
        out = THEMES / tid / "theme_ui.c"
        out.parent.mkdir(parents=True, exist_ok=True)
        text = wrap(tid, home)
        out.write_text(text, encoding="utf-8", newline="\n")
        written.append(out)
        print(f"wrote {out} ({len(text.splitlines())} lines)")
    print(f"done: {len(written)} theme packs")


if __name__ == "__main__":
    main()
