#!/usr/bin/env python3
"""P3: split each hub theme_pack.c into a manageable folder + deep restore patches.

Layout per ui/themes/<id>/:
  theme_local.h  palette.c  theme_local.c  home.c
  pages_room.c  pages_scenes.c  pages_ops.c  pages_life.c  boot.c

Also deletes theme_pack.c after successful split.
Run: python tools/gen_p3_split_themes.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = ROOT / "ui" / "themes"
THEME_IDS = (
    "slate",
    "sand",
    "ink",
    "forest",
    "dusk",
    "ocean",
    "zen",
    "pulse",
    "bloom",
    "metro",
)

COMMON_INCLUDES = """\
#include "theme_local.h"
#include "hub_ui.h"
#include "hub_theme.h"
#include "hub_font.h"
#include "hub_model.h"
#include "hub_icons.h"
#include "app_ui.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>
"""

LOCAL_H = """\
/**
 * {name} theme-local API (folder-private; not shared across themes).
 * Generated by tools/gen_p3_split_themes.py
 */
#pragma once

#include "hub_ui.h"
#include "hub_theme.h"
#include "lvgl.h"
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {{
#endif

void go_cb(lv_event_t *e);
void scene_cb(lv_event_t *e);
void proto_cb(lv_event_t *e);
void room_cb(lv_event_t *e);
void arm_cb(lv_event_t *e);
void zone_cb(lv_event_t *e);
void toggle_dev_cb(lv_event_t *e);
void step_ac_cb(lv_event_t *e);
void step_curtain_cb(lv_event_t *e);
void strip_step_cb(lv_event_t *e);
void curtain_set_cb(lv_event_t *e);

lv_obj_t *lbl(lv_obj_t *par, const char *txt, lv_color_t c, const lv_font_t *f);
lv_obj_t *btn_go(lv_obj_t *par, const char *txt, hub_route_t r, bool accent);
void quickbar(lv_obj_t *par);

/** Theme visual language applied after hub_apply_card */
void theme_card_chrome(lv_obj_t *obj, bool active);

void build_home(lv_obj_t *parent);
void build_room(lv_obj_t *parent);
void build_scenes(lv_obj_t *parent);
void build_energy(lv_obj_t *parent);
void build_gateway(lv_obj_t *parent);
void build_settings(lv_obj_t *parent);
void build_network(lv_obj_t *parent);
void build_security(lv_obj_t *parent);
void build_schedule(lv_obj_t *parent);
void build_hvac(lv_obj_t *parent);
void build_points(lv_obj_t *parent);

#ifdef __cplusplus
}}
#endif
"""

# Per-theme chrome injected into theme_local.c
CHROME = {
    "slate": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, p->radius, 0);
    if (active) {
        lv_obj_set_style_border_side(obj, LV_BORDER_SIDE_LEFT, 0);
        lv_obj_set_style_border_width(obj, 3, 0);
        lv_obj_set_style_border_color(obj, p->accent, 0);
    }
}
""",
    "sand": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    (void)active;
    lv_obj_set_style_radius(obj, 16, 0);
    lv_obj_set_style_pad_all(obj, 4, 0);
    lv_obj_set_style_shadow_width(obj, 8, 0);
    lv_obj_set_style_shadow_opa(obj, LV_OPA_20, 0);
    lv_obj_set_style_shadow_color(obj, p->t4, 0);
    lv_obj_set_style_shadow_ofs_y(obj, 4, 0);
}
""",
    "ink": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, p->radius_sm, 0);
    lv_obj_set_style_border_width(obj, 1, 0);
    lv_obj_set_style_border_color(obj, active ? p->accent : p->line, 0);
}
""",
    "forest": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, p->radius, 0);
    if (active) {
        lv_obj_set_style_border_width(obj, 2, 0);
        lv_obj_set_style_border_color(obj, p->accent, 0);
    }
}
""",
    "dusk": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, p->radius, 0);
    lv_obj_set_style_bg_opa(obj, active ? LV_OPA_COVER : LV_OPA_80, 0);
    lv_obj_set_style_border_color(obj, p->violet, 0);
    lv_obj_set_style_border_width(obj, 1, 0);
}
""",
    "ocean": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, p->radius_sm, 0);
    if (active) {
        lv_obj_set_style_outline_width(obj, 1, 0);
        lv_obj_set_style_outline_color(obj, p->cool, 0);
        lv_obj_set_style_outline_opa(obj, LV_OPA_COVER, 0);
    }
}
""",
    "zen": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    (void)active;
    lv_obj_set_style_radius(obj, 4, 0);
    lv_obj_set_style_border_width(obj, 1, 0);
    lv_obj_set_style_border_color(obj, p->line, 0);
    lv_obj_set_style_pad_row(obj, 6, 0);
}
""",
    "pulse": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    hub_hud_bevel(obj, p->accent);
    if (active) {
        lv_obj_set_style_border_color(obj, p->accent, 0);
        lv_obj_set_style_border_width(obj, 2, 0);
    }
}
""",
    "bloom": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    (void)active;
    lv_obj_set_style_radius(obj, 28, 0);
    lv_obj_set_style_shadow_width(obj, 16, 0);
    lv_obj_set_style_shadow_opa(obj, LV_OPA_20, 0);
    lv_obj_set_style_shadow_color(obj, p->accent, 0);
    lv_obj_set_style_shadow_ofs_y(obj, 6, 0);
}
""",
    "metro": """
void theme_card_chrome(lv_obj_t *obj, bool active)
{
    const hub_palette_t *p = hub_palette();
    lv_obj_set_style_radius(obj, 0, 0);
    if (active) {
        lv_obj_set_style_bg_color(obj, p->accent, 0);
        lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
    }
}
""",
}

EXTRA_CBS = r'''
void toggle_dev_cb(lv_event_t *e)
{
    int kind = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[m->room_idx];
    if (kind == 0) {
        d->ceiling = !d->ceiling;
    } else if (kind == 1) {
        d->strip = d->strip > 0 ? 0 : 55;
    } else if (kind == 3) {
        d->ac_on = !d->ac_on;
    } else if (kind == 4) {
        d->heat_on = !d->heat_on;
    } else if (kind == 6) {
        d->fan_on = !d->fan_on;
    }
    hub_ui_refresh();
}

void step_ac_cb(lv_event_t *e)
{
    int delta = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_step_ac(delta);
    hub_ui_refresh();
}

void step_curtain_cb(lv_event_t *e)
{
    int delta = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_step_curtain(delta);
    hub_ui_refresh();
}

void strip_step_cb(lv_event_t *e)
{
    int delta = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_step_strip(delta);
    hub_ui_refresh();
}

void curtain_set_cb(lv_event_t *e)
{
    int level = (int)(intptr_t)lv_event_get_user_data(e);
    hub_model_t *m = hub_model();
    m->rooms[m->room_idx].curtain = level;
    hub_ui_refresh();
}
'''


def slice_between(text: str, start_pat: str, end_pat: str | None) -> str:
    sm = re.search(start_pat, text)
    if not sm:
        raise RuntimeError(f"start not found: {start_pat}")
    start = sm.start()
    if end_pat is None:
        return text[start:]
    em = re.search(end_pat, text[sm.end() :])
    if not em:
        raise RuntimeError(f"end not found: {end_pat}")
    return text[start : sm.end() + em.start()]


def destatic(block: str) -> str:
    block = re.sub(r"^static void ", "void ", block, flags=re.M)
    block = re.sub(r"^static char ", "char ", block, flags=re.M)
    block = re.sub(r"^static lv_obj_t \*", "lv_obj_t *", block, flags=re.M)
    return block


def extract_helpers(text: str) -> str:
    block = slice_between(
        text,
        r"/\* ── local helpers.*?\n",
        r"/\* ── HOME",
    )
    # drop the marker line
    block = re.sub(r"^/\* ── local helpers.*\n", "", block)
    block = destatic(block)
    # remove toggle/step if present later — they live in ROOM in packs
    return block.strip() + "\n"


def extract_palette(text: str) -> str:
    m = re.search(
        r"(static const hub_palette_t s_pal = \{.*?\n\};\n\n"
        r"const hub_palette_t \*hub_palette\(void\)\n\{\n    return &s_pal;\n\}\n)",
        text,
        re.S,
    )
    if not m:
        raise RuntimeError("palette extract failed")
    return m.group(1)


def extract_fn_block(text: str, name: str, next_names: tuple[str, ...]) -> str:
    start = re.search(rf"(?:static )?void {name}\(lv_obj_t \*parent\)\s*\n\{{", text)
    if not start:
        raise RuntimeError(f"fn {name} not found")
    rest = text[start.end() :]
    # find matching close by scanning braces from the opening we already consumed
    depth = 1
    i = 0
    while i < len(rest) and depth:
        if rest[i] == "{":
            depth += 1
        elif rest[i] == "}":
            depth -= 1
        i += 1
    body = text[start.start() : start.end() + i]
    return destatic(body)


def extract_until_marker(text: str, start_re: str, end_re: str) -> str:
    sm = re.search(start_re, text)
    if not sm:
        raise RuntimeError(start_re)
    em = re.search(end_re, text[sm.start() + 1 :])
    if not em:
        raise RuntimeError(end_re)
    return destatic(text[sm.start() : sm.start() + 1 + em.start()])


def patch_home(tid: str, home: str) -> str:
    h = home

    if tid == "slate":
        h = h.replace(
            "hub_route_t mrs[] = { HUB_ROUTE_ENERGY, HUB_ROUTE_ROOM, HUB_ROUTE_ROOM };",
            "hub_route_t mrs[] = { HUB_ROUTE_ENERGY, HUB_ROUTE_HVAC, HUB_ROUTE_HVAC };",
        )

    if tid == "forest":
        h = h.replace(
            'const char *ids[] = {"morning", "guest", "movie", "sleep", "eco", "alloff"};',
            'const char *ids[] = {"home", "guest", "movie", "sleep", "eco", "alloff"};',
        )

    if tid == "sand":
        # 3 rooms like FE; orb radius 20 (rounded square)
        h = h.replace(
            "lv_obj_set_style_radius(pwr, LV_RADIUS_CIRCLE, 0);",
            "lv_obj_set_style_radius(pwr, 20, 0);",
        )
        h = h.replace(
            """    const char *subs[] = {"空调 · 窗帘 · 灯", "地暖 · 灯光", "插座 · 水阀", "灯光 · 窗帘"};
    for (int i = 0; i < 4; i++) {""",
            """    const char *subs[] = {"空调 · 窗帘 · 灯", "地暖 · 灯光", "插座 · 水阀"};
    for (int i = 0; i < 3; i++) {""",
        )

    if tid == "bloom":
        h = h.replace(
            "lv_obj_add_event_cb(orb, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);",
            "lv_obj_add_event_cb(orb, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_HVAC);",
        )
        old_grid = """    for (int i = 0; i < 4; i++) {
        bool on = hub_model_room_active(i);
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        lv_obj_set_style_radius(b, 28, 0);
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        hub_ico_add(b, HUB_ICO_HOME, p->accent, 20);
        lv_obj_align(lv_obj_get_child(b, 0), LV_ALIGN_TOP_LEFT, 14, 14);
        lbl(b, hub_model_room_name(i), p->t1, hub_font());
        lv_obj_align(lv_obj_get_child(b, 1), LV_ALIGN_BOTTOM_LEFT, 14, -28);
        lbl(b, on ? "柔光开启" : "已入睡", p->t3, hub_font());
        lv_obj_align(lv_obj_get_child(b, 2), LV_ALIGN_BOTTOM_LEFT, 14, -10);
    }"""
        new_grid = """    lv_color_t hues[] = {
        LV_COLOR_MAKE(0xe8, 0x91, 0xa8), LV_COLOR_MAKE(0x7e, 0xb8, 0xc9),
        LV_COLOR_MAKE(0xe8, 0xa0, 0x6a), LV_COLOR_MAKE(0xb8, 0xa0, 0xd0),
    };
    for (int i = 0; i < 4; i++) {
        bool on = hub_model_room_active(i);
        lv_obj_t *b = lv_btn_create(grid);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, on);
        theme_card_chrome(b, on);
        lv_obj_set_style_radius(b, 28, 0);
        if (on) {
            lv_obj_set_style_bg_color(b, hues[i], 0);
            lv_obj_set_style_bg_opa(b, LV_OPA_40, 0);
        }
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        hub_ico_add(b, HUB_ICO_HOME, hues[i], 20);
        lv_obj_align(lv_obj_get_child(b, 0), LV_ALIGN_TOP_LEFT, 14, 14);
        lbl(b, hub_model_room_name(i), p->t1, hub_font());
        lv_obj_align(lv_obj_get_child(b, 1), LV_ALIGN_BOTTOM_LEFT, 14, -28);
        lbl(b, on ? "柔光开启" : "已入睡", p->t3, hub_font());
        lv_obj_align(lv_obj_get_child(b, 2), LV_ALIGN_BOTTOM_LEFT, 14, -10);
    }"""
        if old_grid not in h:
            raise RuntimeError("bloom grid block missing")
        h = h.replace(old_grid, new_grid)

    if tid == "pulse":
        needle = """    lbl(pwr, "kW", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(pwr, 2), LV_ALIGN_LEFT_MID, 90, 8);

    lv_obj_t *bus = lv_btn_create(hud);"""
        bar = """    lbl(pwr, "kW", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(pwr, 2), LV_ALIGN_LEFT_MID, 90, 8);
    lv_obj_t *bar_bg = lv_obj_create(pwr);
    lv_obj_remove_style_all(bar_bg);
    lv_obj_set_size(bar_bg, LV_PCT(90), 4);
    lv_obj_align(bar_bg, LV_ALIGN_BOTTOM_LEFT, 8, -10);
    lv_obj_set_style_bg_color(bar_bg, p->accent, 0);
    lv_obj_set_style_bg_opa(bar_bg, LV_OPA_20, 0);
    lv_obj_t *bar_fg = lv_obj_create(bar_bg);
    lv_obj_remove_style_all(bar_fg);
    int pct = (int)(m->power_kw * 28.0f);
    if (pct > 100) {
        pct = 100;
    }
    if (pct < 8) {
        pct = 8;
    }
    lv_obj_set_size(bar_fg, LV_PCT(pct), 4);
    lv_obj_set_style_bg_color(bar_fg, p->accent, 0);
    lv_obj_set_style_bg_opa(bar_fg, LV_OPA_COVER, 0);
    lv_obj_align(bar_fg, LV_ALIGN_LEFT_MID, 0, 0);

    lv_obj_t *bus = lv_btn_create(hud);"""
        if needle not in h:
            raise RuntimeError("pulse pwr bar insert point missing")
        h = h.replace(needle, bar)

    # Generic: after hub_apply_card(x, y) on home buttons, add chrome where missing
    # (bloom already has theme_card_chrome in patched grid)
    return h


DEEP_ROOM = r'''
void build_room(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[m->room_idx];

    lv_obj_t *shell = hub_shell_create(parent, hub_model_room_name(m->room_idx), true);
    lv_obj_t *body = hub_shell_body(shell);
    hub_shell_set_dots(shell, 4, 1);

    lv_obj_t *tabs = lv_obj_create(body);
    lv_obj_remove_style_all(tabs);
    lv_obj_set_width(tabs, LV_PCT(100));
    lv_obj_set_height(tabs, 36);
    lv_obj_set_flex_flow(tabs, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(tabs, 6, 0);
    for (int i = 0; i < 4; i++) {
        lv_obj_t *t = lv_btn_create(tabs);
        lv_obj_remove_style_all(t);
        hub_apply_card(t, i == m->room_idx);
        theme_card_chrome(t, i == m->room_idx);
        if (i == m->room_idx) {
            lv_obj_set_style_bg_color(t, p->accent, 0);
            lv_obj_set_style_bg_opa(t, LV_OPA_COVER, 0);
        }
        lv_obj_set_flex_grow(t, 1);
        lv_obj_set_height(t, LV_PCT(100));
        lv_obj_add_event_cb(t, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        lv_obj_t *tl = lv_label_create(t);
        lv_label_set_text(tl, hub_model_room_name(i));
        hub_style_label(tl, i == m->room_idx ? p->ink_on : p->t1, hub_font());
        lv_obj_center(tl);
    }

    /* 主灯 */
    lv_obj_t *c0 = lv_btn_create(body);
    lv_obj_remove_style_all(c0);
    hub_apply_card(c0, d->ceiling);
    theme_card_chrome(c0, d->ceiling);
    lv_obj_set_width(c0, LV_PCT(100));
    lv_obj_set_height(c0, 52);
    lv_obj_add_event_cb(c0, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)0);
    hub_ico_add(c0, HUB_ICO_BULB, p->accent, 22);
    lv_obj_align(lv_obj_get_child(c0, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c0, "主灯", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c0, 1), LV_ALIGN_LEFT_MID, 40, 0);
    lbl(c0, d->ceiling ? "开" : "关", d->ceiling ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c0, 2), LV_ALIGN_RIGHT_MID, -8, 0);

    /* 灯带 ± */
    lv_obj_t *c1 = lv_obj_create(body);
    lv_obj_remove_style_all(c1);
    hub_apply_card(c1, d->strip > 0);
    theme_card_chrome(c1, d->strip > 0);
    lv_obj_set_width(c1, LV_PCT(100));
    lv_obj_set_height(c1, 56);
    hub_ico_add(c1, HUB_ICO_BULB, p->warm, 22);
    lv_obj_align(lv_obj_get_child(c1, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c1, "灯带", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c1, 1), LV_ALIGN_LEFT_MID, 40, -8);
    char strip_buf[16];
    snprintf(strip_buf, sizeof(strip_buf), d->strip > 0 ? "%d%%" : "关", d->strip);
    lbl(c1, strip_buf, d->strip > 0 ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c1, 2), LV_ALIGN_LEFT_MID, 40, 10);
    lv_obj_t *sm = lv_btn_create(c1);
    lv_obj_remove_style_all(sm);
    hub_apply_card(sm, false);
    lv_obj_set_size(sm, 40, 40);
    lv_obj_align(sm, LV_ALIGN_RIGHT_MID, -56, 0);
    lv_obj_add_event_cb(sm, strip_step_cb, LV_EVENT_CLICKED, (void *)(intptr_t)-15);
    hub_ico_add(sm, HUB_ICO_MINUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(sm, 0));
    lv_obj_t *sp = lv_btn_create(c1);
    lv_obj_remove_style_all(sp);
    hub_apply_card(sp, false);
    lv_obj_set_size(sp, 40, 40);
    lv_obj_align(sp, LV_ALIGN_RIGHT_MID, -8, 0);
    lv_obj_add_event_cb(sp, strip_step_cb, LV_EVENT_CLICKED, (void *)(intptr_t)15);
    hub_ico_add(sp, HUB_ICO_PLUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(sp, 0));

    /* 窗帘：开 / 半 / 关 */
    lv_obj_t *c2 = lv_obj_create(body);
    lv_obj_remove_style_all(c2);
    hub_apply_card(c2, d->curtain > 50);
    theme_card_chrome(c2, d->curtain > 50);
    lv_obj_set_width(c2, LV_PCT(100));
    lv_obj_set_height(c2, 72);
    hub_ico_add(c2, HUB_ICO_CURTAIN, p->violet, 22);
    lv_obj_align(lv_obj_get_child(c2, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c2, "窗帘", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c2, 1), LV_ALIGN_LEFT_MID, 40, -12);
    char cur_buf[16];
    snprintf(cur_buf, sizeof(cur_buf), "%d%%", d->curtain);
    lbl(c2, cur_buf, p->t2, hub_font());
    lv_obj_align(lv_obj_get_child(c2, 2), LV_ALIGN_LEFT_MID, 40, 8);
    const char *clabs[] = {"开", "半", "关"};
    const int cvals[] = {100, 50, 0};
    for (int i = 0; i < 3; i++) {
        lv_obj_t *b = lv_btn_create(c2);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, d->curtain == cvals[i]);
        theme_card_chrome(b, d->curtain == cvals[i]);
        lv_obj_set_size(b, 44, 36);
        lv_obj_align(b, LV_ALIGN_RIGHT_MID, -8 - (2 - i) * 50, 0);
        lv_obj_add_event_cb(b, curtain_set_cb, LV_EVENT_CLICKED, (void *)(intptr_t)cvals[i]);
        lv_obj_t *bl = lv_label_create(b);
        lv_label_set_text(bl, clabs[i]);
        hub_style_label(bl, p->t1, hub_font());
        lv_obj_center(bl);
    }

    /* 空调 */
    lv_obj_t *c3 = lv_obj_create(body);
    lv_obj_remove_style_all(c3);
    hub_apply_card(c3, d->ac_on);
    theme_card_chrome(c3, d->ac_on);
    lv_obj_set_width(c3, LV_PCT(100));
    lv_obj_set_height(c3, 64);
    hub_ico_add(c3, HUB_ICO_SNOW, p->cool, 22);
    lv_obj_align(lv_obj_get_child(c3, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lv_obj_t *ac_tog = lv_btn_create(c3);
    lv_obj_remove_style_all(ac_tog);
    lv_obj_set_size(ac_tog, 100, 48);
    lv_obj_align(ac_tog, LV_ALIGN_LEFT_MID, 36, 0);
    lv_obj_add_event_cb(ac_tog, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)3);
    lbl(ac_tog, "空调", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(ac_tog, 0), LV_ALIGN_TOP_LEFT, 0, 4);
    char ac_buf[16];
    snprintf(ac_buf, sizeof(ac_buf), d->ac_on ? "%d°" : "关", d->ac_sp);
    lbl(ac_tog, ac_buf, d->ac_on ? p->cool : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ac_tog, 1), LV_ALIGN_BOTTOM_LEFT, 0, -4);
    lv_obj_t *am = lv_btn_create(c3);
    lv_obj_remove_style_all(am);
    hub_apply_card(am, false);
    lv_obj_set_size(am, 40, 40);
    lv_obj_align(am, LV_ALIGN_RIGHT_MID, -56, 0);
    lv_obj_add_event_cb(am, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)-1);
    hub_ico_add(am, HUB_ICO_MINUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(am, 0));
    lv_obj_t *ap = lv_btn_create(c3);
    lv_obj_remove_style_all(ap);
    hub_apply_card(ap, false);
    lv_obj_set_size(ap, 40, 40);
    lv_obj_align(ap, LV_ALIGN_RIGHT_MID, -8, 0);
    lv_obj_add_event_cb(ap, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)1);
    hub_ico_add(ap, HUB_ICO_PLUS, p->t1, 16);
    lv_obj_center(lv_obj_get_child(ap, 0));

    /* 地暖 + 风扇 */
    lv_obj_t *row = lv_obj_create(body);
    lv_obj_remove_style_all(row);
    lv_obj_set_width(row, LV_PCT(100));
    lv_obj_set_height(row, 56);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(row, 8, 0);

    lv_obj_t *c4 = lv_btn_create(row);
    lv_obj_remove_style_all(c4);
    hub_apply_card(c4, d->heat_on);
    theme_card_chrome(c4, d->heat_on);
    lv_obj_set_flex_grow(c4, 1);
    lv_obj_set_height(c4, LV_PCT(100));
    lv_obj_add_event_cb(c4, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)4);
    hub_ico_add(c4, HUB_ICO_HEAT, p->heat, 20);
    lv_obj_align(lv_obj_get_child(c4, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c4, "地暖", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c4, 1), LV_ALIGN_LEFT_MID, 36, 0);
    lbl(c4, d->heat_on ? "开" : "关", d->heat_on ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c4, 2), LV_ALIGN_RIGHT_MID, -8, 0);

    lv_obj_t *c5 = lv_btn_create(row);
    lv_obj_remove_style_all(c5);
    hub_apply_card(c5, d->fan_on);
    theme_card_chrome(c5, d->fan_on);
    lv_obj_set_flex_grow(c5, 1);
    lv_obj_set_height(c5, LV_PCT(100));
    lv_obj_add_event_cb(c5, toggle_dev_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)6);
    hub_ico_add(c5, HUB_ICO_GAUGE, p->cool, 20);
    lv_obj_align(lv_obj_get_child(c5, 0), LV_ALIGN_LEFT_MID, 8, 0);
    lbl(c5, "风扇", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(c5, 1), LV_ALIGN_LEFT_MID, 36, 0);
    lbl(c5, d->fan_on ? "开" : "关", d->fan_on ? p->on : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(c5, 2), LV_ALIGN_RIGHT_MID, -8, 0);

    lv_obj_t *goto_hvac = lv_btn_create(body);
    lv_obj_remove_style_all(goto_hvac);
    hub_apply_card(goto_hvac, true);
    theme_card_chrome(goto_hvac, true);
    lv_obj_set_style_bg_color(goto_hvac, p->accent, 0);
    lv_obj_set_width(goto_hvac, LV_PCT(100));
    lv_obj_set_height(goto_hvac, 44);
    lv_obj_add_event_cb(goto_hvac, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_HVAC);
    lv_obj_t *gl = lv_label_create(goto_hvac);
    lv_label_set_text(gl, "温控详情");
    hub_style_label(gl, p->ink_on, hub_font());
    lv_obj_center(gl);
}
'''


def polish_pages(block: str) -> str:
    """Insert theme_card_chrome after hub_apply_card in page builders."""
    # Avoid double-insert
    out = []
    for line in block.splitlines(keepends=True):
        out.append(line)
        m = re.match(r"(\s*)hub_apply_card\(([^,]+),\s*([^)]+)\);\s*$", line)
        if m and "theme_card_chrome" not in line:
            indent, obj, act = m.group(1), m.group(2).strip(), m.group(3).strip()
            # skip nested tiny buttons sometimes — still OK to chrome
            out.append(f"{indent}theme_card_chrome({obj}, {act});\n")
    return "".join(out)


def write_theme(tid: str) -> None:
    pack = THEMES / tid / "theme_pack.c"
    if not pack.exists():
        # already split? try reading home.c
        raise FileNotFoundError(pack)
    text = pack.read_text(encoding="utf-8")
    name = tid.capitalize()
    out_dir = THEMES / tid

    palette = extract_palette(text)
    helpers = extract_helpers(text)

    # HOME
    home_m = re.search(r"(?:static )?void build_home\(lv_obj_t \*parent\)\s*\n\{", text)
    if not home_m:
        raise RuntimeError(f"{tid}: build_home missing")
    # extract full function with brace match
    home = extract_fn_block(text, "build_home", ())
    home = patch_home(tid, home)

    # Extract page sections from original for ops/life/scenes — but room is deep rewrite
    scenes = extract_fn_block(text, "build_scenes", ())
    scenes = polish_pages(scenes)

    energy = extract_fn_block(text, "build_energy", ())
    gateway = extract_fn_block(text, "build_gateway", ())
    network = extract_fn_block(text, "build_network", ())
    # points: include point_tap_cb
    pt = re.search(r"(?:static )?void point_tap_cb", text)
    bp = re.search(r"(?:static )?void build_points", text)
    if not pt or not bp:
        raise RuntimeError(f"{tid}: points missing")
    points_block = destatic(text[pt.start() : bp.start()]) + extract_fn_block(text, "build_points", ())
    points_block = polish_pages(points_block)

    settings = extract_fn_block(text, "build_settings", ())
    # security includes pin
    pin = re.search(r"(?:static )?char s_pin_buf", text)
    sec = re.search(r"(?:static )?void build_security", text)
    if not pin or not sec:
        raise RuntimeError(f"{tid}: security missing")
    # from s_pin_buf through end of build_security
    sec_start = pin.start()
    # find build_schedule after security
    sch = re.search(r"(?:static )?void build_schedule", text)
    hvac_m = re.search(r"(?:static )?void build_hvac", text)
    if not sch or not hvac_m:
        raise RuntimeError(f"{tid}: schedule/hvac missing")
    security_block = destatic(text[sec_start : sch.start()])
    schedule = extract_fn_block(text, "build_schedule", ())
    hvac = extract_fn_block(text, "build_hvac", ())

    settings = polish_pages(settings)
    security_block = polish_pages(security_block)
    schedule = polish_pages(schedule)
    hvac = polish_pages(hvac)
    energy = polish_pages(energy)
    gateway = polish_pages(gateway)
    network = polish_pages(network)

    # Files
    (out_dir / "theme_local.h").write_text(LOCAL_H.format(name=name), encoding="utf-8", newline="\n")

    (out_dir / "palette.c").write_text(
        f"/** {name} palette */\n#include \"hub_theme.h\"\n\n{palette}",
        encoding="utf-8",
        newline="\n",
    )

    local_c = (
        f"/** {name} theme-local helpers + chrome */\n"
        + COMMON_INCLUDES
        + "\n"
        + helpers
        + "\n"
        + EXTRA_CBS
        + "\n"
        + CHROME[tid].lstrip("\n")
    )
    (out_dir / "theme_local.c").write_text(local_c, encoding="utf-8", newline="\n")

    (out_dir / "home.c").write_text(
        f"/** {name} home */\n{COMMON_INCLUDES}\n{home}\n",
        encoding="utf-8",
        newline="\n",
    )

    (out_dir / "pages_room.c").write_text(
        f"/** {name} room page (deep widgets) */\n{COMMON_INCLUDES}\n{DEEP_ROOM}\n",
        encoding="utf-8",
        newline="\n",
    )

    (out_dir / "pages_scenes.c").write_text(
        f"/** {name} scenes */\n{COMMON_INCLUDES}\n{scenes}\n",
        encoding="utf-8",
        newline="\n",
    )

    ops = f"{energy}\n\n{gateway}\n\n{network}\n\n{points_block}\n"
    (out_dir / "pages_ops.c").write_text(
        f"/** {name} energy / gateway / network / points */\n{COMMON_INCLUDES}\n{ops}",
        encoding="utf-8",
        newline="\n",
    )

    life = f"{settings}\n\n{security_block}\n{schedule}\n\n{hvac}\n"
    (out_dir / "pages_life.c").write_text(
        f"/** {name} settings / security / schedule / hvac */\n{COMMON_INCLUDES}\n{life}",
        encoding="utf-8",
        newline="\n",
    )

    boot = f"""/** {name} boot */
{COMMON_INCLUDES}

void hub_theme_build(lv_obj_t *parent, hub_route_t route)
{{
    switch (route) {{
    case HUB_ROUTE_HOME: build_home(parent); break;
    case HUB_ROUTE_ROOM: build_room(parent); break;
    case HUB_ROUTE_SCENES: build_scenes(parent); break;
    case HUB_ROUTE_ENERGY: build_energy(parent); break;
    case HUB_ROUTE_GATEWAY: build_gateway(parent); break;
    case HUB_ROUTE_SETTINGS: build_settings(parent); break;
    case HUB_ROUTE_NETWORK: build_network(parent); break;
    case HUB_ROUTE_SECURITY: build_security(parent); break;
    case HUB_ROUTE_SCHEDULE: build_schedule(parent); break;
    case HUB_ROUTE_HVAC: build_hvac(parent); break;
    case HUB_ROUTE_POINTS: build_points(parent); break;
    default: build_home(parent); break;
    }}
}}

void app_ui_start(void)
{{
    hub_ui_init();
}}
"""
    (out_dir / "boot.c").write_text(boot, encoding="utf-8", newline="\n")

    # README for folder
    (out_dir / "README.md").write_text(
        f"""# {name} theme pack

Compile-time hub theme. Sources are theme-local (not shared with other themes).

| File | Role |
|------|------|
| `palette.c` | Colors / radius |
| `theme_local.h/.c` | Helpers, callbacks, `theme_card_chrome` |
| `home.c` | Home IA + bindings |
| `pages_room.c` | Room widgets (toggle / curtain / AC / fan) |
| `pages_scenes.c` | Scenes |
| `pages_ops.c` | Energy / gateway / network / points |
| `pages_life.c` | Settings / security / schedule / HVAC |
| `boot.c` | `hub_theme_build` + `app_ui_start` |

Select via `main/app_ui_theme_select.h` → `APP_UI_THEME_{tid.upper()}`.
""",
        encoding="utf-8",
        newline="\n",
    )

    pack.unlink()
    print(f"split {tid} → {out_dir} (deleted theme_pack.c)")


def main() -> None:
    # Add strip step to model before generating room that needs it
    issues = []
    for tid in THEME_IDS:
        try:
            write_theme(tid)
        except Exception as exc:  # noqa: BLE001
            issues.append(f"{tid}: {exc}")
            print(f"FAIL {tid}: {exc}", file=sys.stderr)
    if issues:
        sys.exit(1)
    print(f"done: {len(THEME_IDS)} theme folders")


if __name__ == "__main__":
    main()
