#!/usr/bin/env python3
"""Generate self-contained theme_pack.c for all 10 hub themes (P2).

One file per theme: palette + helpers + home + pages + app_ui_start.
Based on tools/gen_p1_all_themes.py with HVAC/POINTS routes and home upgrades.
Run: python tools/gen_p2_all_themes.py
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = ROOT / "ui" / "themes"
THEME_IDS = (
    "slate",
    "sand",
    "ink",
    "forest",
    "dusk",
    "ocean",
    "zen",
    "pulse",
    "bloom",
    "metro",
)

OLD_THEME_FILES = (
    "theme_home.c",
    "theme_ui.c",
    "theme.c",
    "theme_palette.c",
)


def _load_p1():
    path = ROOT / "tools" / "gen_p1_all_themes.py"
    spec = importlib.util.spec_from_file_location("gen_p1_all_themes", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


HEADER = r'''/**
 * {name} theme pack - P2 self-contained (palette + UI + boot).
 * Generated by tools/gen_p2_all_themes.py - do not hand-edit permanently.
 */
#include "hub_ui.h"
#include "hub_theme.h"
#include "hub_font.h"
#include "hub_model.h"
#include "hub_icons.h"
#include "app_ui.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>

'''

HELPERS = r'''
/* ── local helpers (theme-local, not shared pages) ───────────────── */

static void go_cb(lv_event_t *e)
{{
    hub_ui_go((hub_route_t)(uintptr_t)lv_event_get_user_data(e));
}}

static void scene_cb(lv_event_t *e)
{{
    const char *id = (const char *)lv_event_get_user_data(e);
    hub_model_apply_scene(id);
    hub_ui_refresh();
}}

static void proto_cb(lv_event_t *e)
{{
    const char *id = (const char *)lv_event_get_user_data(e);
    hub_model_toggle_proto(id);
    hub_ui_refresh();
}}

static void room_cb(lv_event_t *e)
{{
    int idx = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_set_room(idx);
    hub_ui_go(HUB_ROUTE_ROOM);
}}

static void arm_cb(lv_event_t *e)
{{
    bool on = (bool)(uintptr_t)lv_event_get_user_data(e);
    hub_model_set_armed(on);
    hub_ui_refresh();
}}

static void zone_cb(lv_event_t *e)
{{
    int cell = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_toggle_zone(cell);
    hub_ui_refresh();
}}

static lv_obj_t *lbl(lv_obj_t *par, const char *txt, lv_color_t c, const lv_font_t *f)
{{
    lv_obj_t *l = lv_label_create(par);
    lv_label_set_text(l, txt ? txt : "");
    hub_style_label(l, c, f);
    return l;
}}

static lv_obj_t *btn_go(lv_obj_t *par, const char *txt, hub_route_t r, bool accent)
{{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *b = lv_btn_create(par);
    lv_obj_remove_style_all(b);
    hub_apply_card(b, accent);
    if (accent) {{
        lv_obj_set_style_bg_color(b, p->accent, 0);
    }}
    lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)r);
    lv_obj_t *l = lv_label_create(b);
    lv_label_set_text(l, txt);
    hub_style_label(l, accent ? p->ink_on : p->t1, hub_font());
    lv_obj_center(l);
    return b;
}}

static void quickbar(lv_obj_t *par)
{{
    const hub_palette_t *p = hub_palette();
    lv_obj_t *bar = lv_obj_create(par);
    lv_obj_remove_style_all(bar);
    lv_obj_set_width(bar, LV_PCT(100));
    lv_obj_set_height(bar, 52);
    lv_obj_set_flex_flow(bar, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(bar, 6, 0);

    struct {{
        hub_ico_t ico;
        const char *t;
        hub_route_t r;
    }} items[] = {{
        {{ HUB_ICO_GRID, "情景", HUB_ROUTE_SCENES }},
        {{ HUB_ICO_SHIELD, "安防", HUB_ROUTE_SECURITY }},
        {{ HUB_ICO_CLOCK, "日程", HUB_ROUTE_SCHEDULE }},
        {{ HUB_ICO_COG, "设置", HUB_ROUTE_SETTINGS }},
    }};
    for (int i = 0; i < 4; i++) {{
        lv_obj_t *b = lv_btn_create(bar);
        lv_obj_remove_style_all(b);
        hub_apply_card(b, false);
        lv_obj_set_flex_grow(b, 1);
        lv_obj_set_height(b, LV_PCT(100));
        lv_obj_set_flex_flow(b, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(b, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_add_event_cb(b, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)items[i].r);
        hub_ico_add(b, items[i].ico, p->accent, 18);
        lbl(b, items[i].t, p->t1, hub_font());
    }}
}}

'''

HVAC_AND_POINTS = r'''
/* ── HVAC ────────────────────────────────────────────────────────── */

static void build_hvac(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[m->room_idx];

    lv_obj_t *shell = hub_shell_create(parent, "温控", true);
    lv_obj_t *body = hub_shell_body(shell);

    lv_obj_t *live = lv_obj_create(body);
    lv_obj_remove_style_all(live);
    lv_obj_set_width(live, LV_PCT(100));
    lv_obj_set_height(live, 64);
    lv_obj_set_flex_flow(live, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(live, 8, 0);
    char ib[32], rb[32];
    snprintf(ib, sizeof(ib), "%.1f°", (double)m->indoor_c);
    snprintf(rb, sizeof(rb), "%d%%", m->rh);
    const char *vals[] = { ib, rb };
    const char *labs[] = { "室内", "湿度" };
    for (int i = 0; i < 2; i++) {
        lv_obj_t *c = lv_obj_create(live);
        lv_obj_remove_style_all(c);
        hub_apply_card(c, false);
        lv_obj_set_flex_grow(c, 1);
        lv_obj_set_height(c, LV_PCT(100));
        lv_obj_t *v = lv_label_create(c);
        lv_label_set_text(v, vals[i]);
        hub_style_label(v, i == 0 ? p->cool : p->violet, hub_font_clock());
        lv_obj_align(v, LV_ALIGN_TOP_MID, 0, 6);
        lv_obj_t *l = lv_label_create(c);
        lv_label_set_text(l, labs[i]);
        hub_style_label(l, p->t3, hub_font());
        lv_obj_align(l, LV_ALIGN_BOTTOM_MID, 0, -6);
    }

    lv_obj_t *ac = lv_obj_create(body);
    lv_obj_remove_style_all(ac);
    hub_apply_card(ac, d->ac_on);
    lv_obj_set_width(ac, LV_PCT(100));
    lv_obj_set_height(ac, 140);
    hub_ico_add(ac, HUB_ICO_SNOW, p->cool, 28);
    lv_obj_align(lv_obj_get_child(ac, 0), LV_ALIGN_TOP_LEFT, 12, 12);
    lbl(ac, "空调", p->t1, hub_font());
    lv_obj_align(lv_obj_get_child(ac, 1), LV_ALIGN_TOP_LEFT, 48, 16);
    lbl(ac, d->ac_on ? "制冷" : "关闭", d->ac_on ? p->cool : p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ac, 2), LV_ALIGN_TOP_RIGHT, -12, 16);

    char sp[16];
    snprintf(sp, sizeof(sp), "%d°", d->ac_sp);
    lv_obj_t *sv = lv_label_create(ac);
    lv_label_set_text(sv, sp);
    hub_style_label(sv, p->t1, hub_font_clock_lg());
    lv_obj_align(sv, LV_ALIGN_LEFT_MID, 12, 8);

    lv_obj_t *am = lv_btn_create(ac);
    lv_obj_remove_style_all(am);
    hub_apply_card(am, false);
    lv_obj_set_size(am, 48, 48);
    lv_obj_align(am, LV_ALIGN_BOTTOM_RIGHT, -68, -12);
    lv_obj_add_event_cb(am, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)-1);
    hub_ico_add(am, HUB_ICO_MINUS, p->t1, 18);
    lv_obj_center(lv_obj_get_child(am, 0));
    lv_obj_t *ap = lv_btn_create(ac);
    lv_obj_remove_style_all(ap);
    hub_apply_card(ap, false);
    lv_obj_set_size(ap, 48, 48);
    lv_obj_align(ap, LV_ALIGN_BOTTOM_RIGHT, -12, -12);
    lv_obj_add_event_cb(ap, step_ac_cb, LV_EVENT_CLICKED, (void *)(intptr_t)1);
    hub_ico_add(ap, HUB_ICO_PLUS, p->t1, 18);
    lv_obj_center(lv_obj_get_child(ap, 0));

    lv_obj_t *go = lv_btn_create(body);
    lv_obj_remove_style_all(go);
    hub_apply_card(go, true);
    lv_obj_set_style_bg_color(go, p->accent, 0);
    lv_obj_set_width(go, LV_PCT(100));
    lv_obj_set_height(go, 48);
    lv_obj_add_event_cb(go, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)m->room_idx);
    lv_obj_t *gl = lv_label_create(go);
    lv_label_set_text(gl, "进入房间");
    hub_style_label(gl, p->ink_on, hub_font());
    lv_obj_center(gl);
}

/* ── POINTS ──────────────────────────────────────────────────────── */

static void point_tap_cb(lv_event_t *e)
{
    int kind = (int)(uintptr_t)lv_event_get_user_data(e);
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];
    if (kind == 0) {
        d->ceiling = !d->ceiling;
        hub_ui_refresh();
    } else if (kind == 1) {
        d->strip = d->strip > 0 ? 0 : 55;
        hub_ui_refresh();
    } else if (kind == 3) {
        d->ac_on = !d->ac_on;
        hub_ui_refresh();
    } else if (kind == 4) {
        d->heat_on = !d->heat_on;
        hub_ui_refresh();
    } else {
        hub_model_set_room(0);
        hub_ui_go(HUB_ROUTE_ROOM);
    }
}

static void build_points(lv_obj_t *parent)
{
    const hub_palette_t *p = hub_palette();
    hub_model_t *m = hub_model();
    hub_room_dev_t *d = &m->rooms[0];

    lv_obj_t *shell = hub_shell_create(parent, "点表", true);
    lv_obj_t *body = hub_shell_body(shell);

    char v_ceil[16], v_strip[16], v_cur[16], v_ac[16], v_heat[16];
    snprintf(v_ceil, sizeof(v_ceil), "%s", d->ceiling ? "On" : "Off");
    snprintf(v_strip, sizeof(v_strip), d->strip > 0 ? "%d%%" : "Off", d->strip);
    snprintf(v_cur, sizeof(v_cur), "%d%%", d->curtain);
    snprintf(v_ac, sizeof(v_ac), d->ac_on ? "%d°" : "Off", d->ac_sp);
    snprintf(v_heat, sizeof(v_heat), "%s", d->heat_on ? "On" : "Off");

    struct {
        hub_ico_t ico;
        const char *name;
        const char *val;
        bool on;
        int kind;
    } rows[] = {
        { HUB_ICO_BULB, "主灯", v_ceil, d->ceiling, 0 },
        { HUB_ICO_BULB, "灯带", v_strip, d->strip > 0, 1 },
        { HUB_ICO_CURTAIN, "窗帘", v_cur, d->curtain > 50, 2 },
        { HUB_ICO_SNOW, "空调", v_ac, d->ac_on, 3 },
        { HUB_ICO_HEAT, "地暖", v_heat, d->heat_on, 4 },
        { HUB_ICO_HOME, "客厅", hub_model_room_name(0), hub_model_room_active(0), 5 },
    };
    for (int i = 0; i < 6; i++) {
        lv_obj_t *row = lv_btn_create(body);
        lv_obj_remove_style_all(row);
        hub_apply_card(row, rows[i].on);
        lv_obj_set_width(row, LV_PCT(100));
        lv_obj_set_height(row, 52);
        lv_obj_add_event_cb(row, point_tap_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)rows[i].kind);
        hub_ico_add(row, rows[i].ico, p->accent, 20);
        lv_obj_align(lv_obj_get_child(row, 0), LV_ALIGN_LEFT_MID, 8, 0);
        lv_obj_t *n = lv_label_create(row);
        lv_label_set_text(n, rows[i].name);
        hub_style_label(n, p->t1, hub_font());
        lv_obj_align(n, LV_ALIGN_LEFT_MID, 40, 0);
        lv_obj_t *v = lv_label_create(row);
        lv_label_set_text(v, rows[i].val);
        hub_style_label(v, rows[i].on ? p->on : p->t3, hub_font());
        lv_obj_align(v, LV_ALIGN_RIGHT_MID, -8, 0);
    }
}

'''

BOOT = r'''
void app_ui_start(void)
{
    hub_ui_init();
}
'''


def extract_palette(theme_id: str) -> str:
    """Prefer standalone theme_palette.c; fall back to existing theme_pack.c."""
    pal_path = THEMES / theme_id / "theme_palette.c"
    pack_path = THEMES / theme_id / "theme_pack.c"
    if pal_path.exists():
        text = pal_path.read_text(encoding="utf-8")
        text = re.sub(r'#include\s+"hub_theme\.h"\s*\n*', "", text)
        return text.strip() + "\n"
    if pack_path.exists():
        text = pack_path.read_text(encoding="utf-8")
        m = re.search(
            r"(static const hub_palette_t s_pal = \{.*?\n\};\n\n"
            r"const hub_palette_t \*hub_palette\(void\)\n\{\n    return &s_pal;\n\}\n)",
            text,
            re.S,
        )
        if not m:
            raise RuntimeError(f"{theme_id}: cannot extract palette from theme_pack.c")
        return m.group(1)
    raise FileNotFoundError(f"{theme_id}: no theme_palette.c or theme_pack.c")


def upgrade_homes(homes: dict[str, str]) -> dict[str, str]:
    out = dict(homes)

    # Sand: power orb 80×80
    out["sand"] = out["sand"].replace(
        "lv_obj_set_size(pwr, 72, 72);",
        "lv_obj_set_size(pwr, 80, 80);",
    )

    # Ocean: 点表 → POINTS
    out["ocean"] = out["ocean"].replace(
        '{ HUB_ICO_LAYERS, "点表", HUB_ROUTE_GATEWAY },',
        '{ HUB_ICO_LAYERS, "点表", HUB_ROUTE_POINTS },',
    )

    # Forest: energy ring + HVAC stats
    forest_old_ring = '''    lv_obj_t *ring = lv_btn_create(root);
    lv_obj_remove_style_all(ring);
    lv_obj_set_size(ring, 148, 148);
    lv_obj_set_style_radius(ring, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_border_width(ring, 10, 0);
    lv_obj_set_style_border_color(ring, p->accent, 0);
    lv_obj_set_style_bg_opa(ring, LV_OPA_TRANSP, 0);
    lv_obj_add_event_cb(ring, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    lbl(ring, "今日用电", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ring, 0), LV_ALIGN_CENTER, 0, -28);
    char kwh[16];
    snprintf(kwh, sizeof(kwh), "%.1f", (double)(12.0 + m->power_kw * 2));
    lv_obj_t *kv = lv_label_create(ring);
    lv_label_set_text(kv, kwh);
    hub_style_label(kv, p->t1, hub_font_clock());
    lv_obj_align(kv, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t *ku = lv_label_create(ring);
    lv_label_set_text(ku, "kWh");
    hub_style_label(ku, p->t3, hub_font());
    lv_obj_align(ku, LV_ALIGN_CENTER, 0, 28);'''

    forest_new_ring = '''    lv_obj_t *ring_c = hub_energy_ring(root, p->accent, p->cool);
    lv_obj_t *ring = lv_obj_get_parent(ring_c);
    lv_obj_add_event_cb(ring, go_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)HUB_ROUTE_ENERGY);
    lbl(ring_c, "今日用电", p->t3, hub_font());
    lv_obj_align(lv_obj_get_child(ring_c, 0), LV_ALIGN_CENTER, 0, -28);
    char kwh[16];
    snprintf(kwh, sizeof(kwh), "%.1f", (double)(12.0 + m->power_kw * 2));
    lv_obj_t *kv = lv_label_create(ring_c);
    lv_label_set_text(kv, kwh);
    hub_style_label(kv, p->t1, hub_font_clock());
    lv_obj_align(kv, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t *ku = lv_label_create(ring_c);
    lv_label_set_text(ku, "kWh");
    hub_style_label(ku, p->t3, hub_font());
    lv_obj_align(ku, LV_ALIGN_CENTER, 0, 28);'''

    if forest_old_ring not in out["forest"]:
        raise RuntimeError("forest ring block not found for P2 upgrade")
    out["forest"] = out["forest"].replace(forest_old_ring, forest_new_ring)
    out["forest"] = out["forest"].replace(
        "hub_route_t rts[] = { HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_GATEWAY };",
        "hub_route_t rts[] = { HUB_ROUTE_HVAC, HUB_ROUTE_HVAC, HUB_ROUTE_GATEWAY };",
    )

    # Pulse: hub_hud_bevel after hub_apply_card on HUD + zone cards
    pulse = out["pulse"]
    pulse = pulse.replace(
        """    lv_obj_t *pwr = lv_btn_create(hud);
    lv_obj_remove_style_all(pwr);
    hub_apply_card(pwr, false);
    lv_obj_set_flex_grow(pwr, 12);""",
        """    lv_obj_t *pwr = lv_btn_create(hud);
    lv_obj_remove_style_all(pwr);
    hub_apply_card(pwr, false);
    hub_hud_bevel(pwr, p->accent);
    lv_obj_set_flex_grow(pwr, 12);""",
    )
    pulse = pulse.replace(
        """    lv_obj_t *bus = lv_btn_create(hud);
    lv_obj_remove_style_all(bus);
    hub_apply_card(bus, false);
    lv_obj_set_flex_grow(bus, 10);""",
        """    lv_obj_t *bus = lv_btn_create(hud);
    lv_obj_remove_style_all(bus);
    hub_apply_card(bus, false);
    hub_hud_bevel(bus, p->accent);
    lv_obj_set_flex_grow(bus, 10);""",
    )
    pulse = pulse.replace(
        """        hub_apply_card(b, active);
        if (active) {
            lv_obj_set_style_border_color(b, p->accent, 0);
            lv_obj_set_style_border_width(b, 2, 0);
        }
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);""",
        """        hub_apply_card(b, active);
        hub_hud_bevel(b, p->accent);
        if (active) {
            lv_obj_set_style_border_color(b, p->accent, 0);
            lv_obj_set_style_border_width(b, 2, 0);
        }
        lv_obj_set_grid_cell(b, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);
        lv_obj_add_event_cb(b, room_cb, LV_EVENT_CLICKED, (void *)(uintptr_t)i);""",
    )
    # SCENE_HOME/AWAY already use scene_cb in P1; assert present
    if 'scene_cb, LV_EVENT_CLICKED, (void *)"home"' not in pulse:
        raise RuntimeError("pulse SCENE_HOME missing scene_cb")
    if 'scene_cb, LV_EVENT_CLICKED, (void *)"away"' not in pulse:
        raise RuntimeError("pulse SCENE_AWAY missing scene_cb")
    out["pulse"] = pulse

    # Metro: 7 tiles only (no settings in grid)
    metro_old = '''    const char *labels[] = {"客厅", "主卧", "厨房", "情景", "总线", "能耗", "安防", "设置"};
    const char *subs[] = {sub0, sub1, "4 pts", m->active_scene, sub_b, sub_e,
                          m->armed ? "布防" : "撤防", "CFG"};
    lv_color_t colors[] = {
        LV_COLOR_MAKE(0x00, 0xbc, 0xf2), LV_COLOR_MAKE(0x87, 0x64, 0xb8), LV_COLOR_MAKE(0x10, 0x7c, 0x10),
        LV_COLOR_MAKE(0xff, 0x8c, 0x00), LV_COLOR_MAKE(0xe7, 0x48, 0x56), LV_COLOR_MAKE(0x00, 0x78, 0xd4),
        LV_COLOR_MAKE(0x5d, 0x5a, 0x58), LV_COLOR_MAKE(0x00, 0x78, 0xd4),
    };
    uint8_t cs[] = {2, 1, 1, 1, 1, 1, 1, 1};
    uint8_t col[] = {0, 2, 0, 1, 2, 0, 1, 2};
    uint8_t row[] = {0, 0, 1, 1, 1, 2, 2, 2};
    int rooms[] = {0, 1, 2, -1, -1, -1, -1, -1};
    hub_route_t routes[] = {
        HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_SCENES,
        HUB_ROUTE_GATEWAY, HUB_ROUTE_ENERGY, HUB_ROUTE_SECURITY, HUB_ROUTE_SETTINGS,
    };
    for (int i = 0; i < 8; i++) {'''

    metro_new = '''    const char *labels[] = {"客厅", "主卧", "厨房", "情景", "总线", "能耗", "安防"};
    const char *subs[] = {sub0, sub1, "4 pts", m->active_scene, sub_b, sub_e,
                          m->armed ? "布防" : "撤防"};
    lv_color_t colors[] = {
        LV_COLOR_MAKE(0x00, 0xbc, 0xf2), LV_COLOR_MAKE(0x87, 0x64, 0xb8), LV_COLOR_MAKE(0x10, 0x7c, 0x10),
        LV_COLOR_MAKE(0xff, 0x8c, 0x00), LV_COLOR_MAKE(0xe7, 0x48, 0x56), LV_COLOR_MAKE(0x00, 0x78, 0xd4),
        LV_COLOR_MAKE(0x5d, 0x5a, 0x58),
    };
    uint8_t cs[] = {2, 1, 1, 1, 1, 1, 1};
    uint8_t col[] = {0, 2, 0, 1, 2, 0, 1};
    uint8_t row[] = {0, 0, 1, 1, 1, 2, 2};
    int rooms[] = {0, 1, 2, -1, -1, -1, -1};
    hub_route_t routes[] = {
        HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_ROOM, HUB_ROUTE_SCENES,
        HUB_ROUTE_GATEWAY, HUB_ROUTE_ENERGY, HUB_ROUTE_SECURITY,
    };
    for (int i = 0; i < 7; i++) {'''

    if metro_old not in out["metro"]:
        raise RuntimeError("metro tile block not found for P2 upgrade")
    out["metro"] = out["metro"].replace(metro_old, metro_new)

    return out


def upgrade_pages(pages: str) -> str:
    # Settings: add 温控 + 点表 rows
    old_settings = '''    } rows[] = {
        { HUB_ICO_WIFI, "网络与配网", "Wi-Fi / 以太网", HUB_ROUTE_NETWORK },
        { HUB_ICO_SHIELD, "安防", "布防 / 撤防", HUB_ROUTE_SECURITY },
        { HUB_ICO_BUS, "总线", "MQTT / Modbus", HUB_ROUTE_GATEWAY },
        { HUB_ICO_HOME, "房间", "控件布局", HUB_ROUTE_ROOM },
        { HUB_ICO_CLOCK, "日程", "定时与场景", HUB_ROUTE_SCHEDULE },
    };
    for (int i = 0; i < 5; i++) {'''

    new_settings = '''    } rows[] = {
        { HUB_ICO_WIFI, "网络与配网", "Wi-Fi / 以太网", HUB_ROUTE_NETWORK },
        { HUB_ICO_SHIELD, "安防", "布防 / 撤防", HUB_ROUTE_SECURITY },
        { HUB_ICO_BUS, "总线", "MQTT / Modbus", HUB_ROUTE_GATEWAY },
        { HUB_ICO_SNOW, "温控", "空调与地暖", HUB_ROUTE_HVAC },
        { HUB_ICO_LAYERS, "点表", "设备点位", HUB_ROUTE_POINTS },
        { HUB_ICO_HOME, "房间", "控件布局", HUB_ROUTE_ROOM },
        { HUB_ICO_CLOCK, "日程", "定时与场景", HUB_ROUTE_SCHEDULE },
    };
    for (int i = 0; i < 7; i++) {'''

    if old_settings not in pages:
        raise RuntimeError("settings rows block not found")
    pages = pages.replace(old_settings, new_settings)

    # Insert HVAC/POINTS before entry, and extend switch
    marker = "/* ── entry ───────────────────────────────────────────────────────── */"
    if marker not in pages:
        raise RuntimeError("entry marker not found in PAGES")
    pages = pages.replace(marker, HVAC_AND_POINTS.lstrip("\n") + marker)

    old_switch = '''    case HUB_ROUTE_SCHEDULE: build_schedule(parent); break;
    default: build_home(parent); break;'''
    new_switch = '''    case HUB_ROUTE_SCHEDULE: build_schedule(parent); break;
    case HUB_ROUTE_HVAC: build_hvac(parent); break;
    case HUB_ROUTE_POINTS: build_points(parent); break;
    default: build_home(parent); break;'''
    if old_switch not in pages:
        raise RuntimeError("hub_theme_build switch not found")
    pages = pages.replace(old_switch, new_switch)
    return pages


def wrap(theme_id: str, palette: str, home: str, pages: str) -> str:
    name = theme_id.capitalize()
    parts = [
        HEADER.format(name=name),
        "/* ── palette ─────────────────────────────────────────────────────── */\n",
        palette,
        "\n",
        HELPERS.format(),  # double braces already escaped
        "/* ── HOME ────────────────────────────────────────────────────────── */\n",
        home.strip(),
        "\n\n",
        pages.lstrip("\n"),
        "\n",
        BOOT.lstrip("\n"),
    ]
    return "".join(parts)


def verify_pack(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    missing = []
    for sym in ("hub_palette", "hub_theme_build", "app_ui_start", "build_hvac", "build_points"):
        if sym not in text:
            missing.append(sym)
    return missing


def main() -> None:
    p1 = _load_p1()
    homes = upgrade_homes(dict(p1.HOMES))
    pages = upgrade_pages(p1.PAGES)

    written: list[Path] = []
    issues: list[str] = []

    for tid in THEME_IDS:
        try:
            palette = extract_palette(tid)
        except (FileNotFoundError, RuntimeError) as exc:
            issues.append(str(exc))
            continue
        out = THEMES / tid / "theme_pack.c"
        out.parent.mkdir(parents=True, exist_ok=True)
        text = wrap(tid, palette, homes[tid], pages)
        out.write_text(text, encoding="utf-8", newline="\n")
        written.append(out)
        miss = verify_pack(out)
        if miss:
            issues.append(f"{tid}: missing symbols {miss}")
        print(f"wrote {out} ({len(text.splitlines())} lines)")

    if len(written) != len(THEME_IDS):
        print(f"ERROR: only wrote {len(written)}/{len(THEME_IDS)} packs", file=sys.stderr)
        sys.exit(1)

    # Cleanup old split files after successful generation
    deleted = []
    for tid in THEME_IDS:
        for name in OLD_THEME_FILES:
            p = THEMES / tid / name
            if p.exists():
                p.unlink()
                deleted.append(p)
                print(f"deleted {p}")

    print(f"done: {len(written)} theme_pack.c, deleted {len(deleted)} old files")
    if issues:
        print("ISSUES:")
        for i in issues:
            print(f"  - {i}")
        sys.exit(1)


if __name__ == "__main__":
    main()
