#!/usr/bin/env python3
"""Merge each hub theme folder into one cohesive theme.c (10 files total).

High cohesion: one theme = one compilation unit.
Low coupling: themes never include each other; only thin hub_ui runtime.

Run: python tools/gen_theme_onefile.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = ROOT / "ui" / "themes"
THEME_IDS = (
    "slate",
    "sand",
    "ink",
    "forest",
    "dusk",
    "ocean",
    "zen",
    "pulse",
    "bloom",
    "metro",
)

PARTS = (
    "palette.c",
    "theme_local.c",
    "home.c",
    "pages_room.c",
    "pages_scenes.c",
    "pages_ops.c",
    "pages_life.c",
    "boot.c",
)

DELETE_AFTER = PARTS + ("theme_local.h",)

HEADER = """\
/**
 * {name} theme — self-contained pack (palette + UI + boot).
 * One file per theme for high cohesion / low coupling across themes.
 * Generated by tools/gen_theme_onefile.py
 */
#include "hub_ui.h"
#include "hub_theme.h"
#include "hub_font.h"
#include "hub_model.h"
#include "hub_icons.h"
#include "app_ui.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>

"""

# Symbols that must remain external (hub runtime contracts)
KEEP_EXTERNAL = (
    "hub_palette",
    "hub_theme_build",
    "app_ui_start",
)


def strip_includes(text: str) -> str:
    text = re.sub(r'^/\*\*.*?\*/\s*', "", text, count=1, flags=re.S)
    lines = []
    for line in text.splitlines(keepends=True):
        if line.startswith("#include"):
            continue
        lines.append(line)
    return "".join(lines).strip() + "\n"


def make_file_local(text: str) -> str:
    """Make internal helpers/builders static; keep hub contracts public."""

    def repl_void(m: re.Match[str]) -> str:
        name = m.group(1)
        if name in KEEP_EXTERNAL:
            return m.group(0)
        return f"static void {name}("

    def repl_ret(m: re.Match[str]) -> str:
        ret, name = m.group(1), m.group(2)
        if name in KEEP_EXTERNAL:
            return m.group(0)
        return f"static {ret}{name}("

    text = re.sub(r"^void ([a-zA-Z_][a-zA-Z0-9_]*)\(", repl_void, text, flags=re.M)
    text = re.sub(
        r"^(lv_obj_t \*|const hub_palette_t \*|char )([a-zA-Z_][a-zA-Z0-9_]*)\(",
        repl_ret,
        text,
        flags=re.M,
    )
    text = re.sub(r"^char (s_pin_buf)", r"static char \1", text, flags=re.M)
    text = text.replace("static static ", "static ")
    return text


def merge_theme(tid: str) -> Path:
    d = THEMES / tid
    missing = [p for p in PARTS if not (d / p).exists()]
    if missing:
        # already onefile?
        if (d / "theme.c").exists():
            print(f"skip {tid}: theme.c already exists, parts missing {missing}")
            return d / "theme.c"
        raise FileNotFoundError(f"{tid}: missing {missing}")

    chunks = [HEADER.format(name=tid.capitalize())]
    for part in PARTS:
        body = strip_includes((d / part).read_text(encoding="utf-8"))
        chunks.append(f"/* ── {part} ─────────────────────────────────────────── */\n")
        chunks.append(body)
        chunks.append("\n")

    text = make_file_local("".join(chunks))
    out = d / "theme.c"
    out.write_text(text, encoding="utf-8", newline="\n")

    for name in DELETE_AFTER:
        p = d / name
        if p.exists():
            p.unlink()

    readme = d / "README.md"
    readme.write_text(
        f"""# {tid.capitalize()} theme

Single self-contained unit: **`theme.c`**

- High cohesion: palette, home, pages, boot in one file
- Low coupling: no includes from other themes; only `main/hub_ui/` runtime

Select: `APP_UI_THEME_{tid.upper()}` in `main/app_ui_theme_select.h`
""",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {out} ({len(text.splitlines())} lines), removed split sources")
    return out


def main() -> None:
    for tid in THEME_IDS:
        merge_theme(tid)
    print(f"done: {len(THEME_IDS)} theme.c files")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
